[package]
name = "gen_rules"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
asciidoc = {path = "../asciidoc"}
character = {path = "../character"}
profiles = {path = "../profiles"}
convert_case = "0.6.*"
