---
title: Character Creation
weight: 14
prev: /docs/basic_concepts
next: /docs/abilities_and_saves
---
:toc:

== Creating a character

Players follow these steps to create a new character.
Many concepts will become clearer in the next chapters.

. *Abilities*.
Roll on the <<tb_starting_ability_scores>> to determine an array of three scores and assign them randomly to the three abilities: Strength (STR), Agility (AGI), and Wits (WIT).

** Roll a d3 to assign the highest score: 1) STR; 2) AGI; 3) WIT.

** Roll a d2 to assign the middle score to one of the remaining abilities, skipping over the one which was already assigned.

** Finally assign the lowest score to the last remaining ability.

. *Background*.
Determine your background by rolling on the <<tb_backgrounds>> table.

** You start with one or two skills granted by your background.

** A few backgrounds increase two abilities by 1.
Adjust their scores if that's the case.

** Reroll if you get the same background as another Player.

. *Secondary properties*.
You start with health equal to your STR, 0 corruption, and 2 omens.
You also start with 0 mana unless your background is _wizard_, in which case you start with 1 mana.

. *Assets*.
You start with d8 shillings (ʂ), the items and followers granted by your background, and the items and shillings you get by rolling once on each of the <<tb_starting_weapons>> and <<tb_starting_items>> tables.

** You additionally share a single _candle_ and _flint & tinder_ with the other Player characters.

** If you start with a _power scroll_ without a specified power, roll for it on the <<tb_sorcerous_powers>> or <<tb_sacred_powers>> tables.

** Reroll if you get the same result as another Player on any table.

. *Name and description*.
Name and portray your character using words, drawings, or a combination of the two, as you prefer.
You can roll on the <<tb_masculine_names>>, <<tb_feminine_names>>, <<tb_last_names>>, <<tb_appearance>>, <<tb_personality>>, and <<tb_reason_to_adventure>> tables if you need inspiration.

++++
{{% details title="Example" closed="true" %}}

David is creating a new character.

1. He rolls 7 on a d12 for the abilities scores: 11, 7, and 6.
He rolls a d3 to assign the highest score (11) and gets a 2 (AGI).
He rolls a d2 to assign the middle score (7) and gets a 2 again (WIT in this case, skipping over AGI).
His character's starting abilities are therefore: **STR** 6, **AGI** 11, **WIT** 7.

2. He rolls a 3 on a d4 and a 4 on a d8 for the background: _labourer_.
This grants him the _brawling_ and _wrestling_ skills and no ability increases.

3. He notes down his secondary properties: health is 6 (equal to STR), corruption is 0, omens are 2, and mana is 0.

4. He starts with the following assets:

    * He rolls 1 on a d8 for starting money: 1ʂ.

    * His background provides: _clothes_, a _shovel_, and a _ration_.

    * He rolls 1 on a d2 and 5 on a d12 for his starting weapon: a _boat hook_ plus 4ʂ.

    * He rolls 2 on a d2 and 1 on a d12 for his starting item: one dose of _flash powder_.

5. He finally describes and name his character.

{{% /details %}}
++++


== Company relationships

After all characters have been created, describe how they know each other.
You can roll on the <<tb_relationships>> table if you need inspiration.
You don't have to do this for every possible pair of characters, but you should make sure that everyone is connected.
You can for example go around the table and define a connection for each pair of Players sitting next to each other, excluding the last pair.


== Character creation tables

include::gen/tb_starting_ability_scores.adoc[]

include::gen/tb_backgrounds.adoc[]

include::gen/tb_starting_weapons.adoc[]

include::gen/tb_starting_items.adoc[]

include::gen/tb_sacred_powers.adoc[]

include::gen/tb_sorcerous_powers.adoc[]

include::gen/tb_appearance.adoc[]

include::gen/tb_personality.adoc[]

include::gen/tb_reason_to_adventure.adoc[]

include::gen/tb_masculine_names.adoc[]

include::gen/tb_feminine_names.adoc[]

include::gen/tb_last_names.adoc[]

include::gen/tb_relationships.adoc[]
