---
title: Character Advancement
weight: 85
prev: /docs/followers_and_services
next: /docs/positioning_and_movement
---
:toc:

== Character improvements

During a campaign, you might be granted an advancement by the GM after you and the other Players achieve significant progress.

* At odd advancements (1st, 3rd, 5th, etc.) you permanently increase your abilities by a total of 2 points, but no ability can exceed 15.

* At even advancements (2nd, 4th, 6th, etc.) you gain a new skill of your choice, but you must be able to reasonably explain how you have learnt it (a mentor, past experiences, etc.).

* Characters with the _sorcery_ skill can alternatively increase their mana by 1 instead of picking a standard advancement.


== Advancement limit

After 10 advancements you have reached the pinnacle of your potential and don't gain these benefits for free any longer.
Instead, you must first either forget a skill, reduce your abilities by a total of 2 points, or reduce your mana by 1.
You can then pick a new advancement as usual.


== Granting advancements

The GM decides when the Player characters advance depending on how they are managing the campaign.
Here are a few common options to give you some inspiration!

* *Scenarios*.
Grant a new advancement upon reaching the goals of a scenario, or of a few scenarios if you want to slow things down.
This method is well suited for episodic campaigns made of a sequence of distinct scenarios.

* *Milestones*.
Grant a new advancement upon completing a significant task or reaching a milestone in the campaign.
This method is well suited for sandbox campaigns where the separation between scenarios is not clear cut.

* *Experience for money*.
The Player characters earn experience points by spending money, at a rate of one experience point per shilling, and advance after gathering specific amounts of experience points.
Money spent in this way is lost and can't be retrieved in any way: it is stashed away for retirement, wasted carousing, donated to a good cause, etc.
The <<tb_experience_and_advancements>> table shows the amount of experience point required to reach certain advancements, but feel free to modify it based on your requirements.
This method is well suited for campaigns where the main goal is gathering treasure.

.Experience and advancements
[[tb_experience_and_advancements]]
[options='header, unbreakable', cols="^2,^4,^2,^4"]
|===
|Advancement |Experience required
|Advancement |Experience required
|1   |200
|2   |400
|3   |800
|4   |1,600
|5   |3,200
|6   |6,400
|7   |12,500
|8   |25,000
|9   |50,000
|10  |100,000
|11+  3+|Add 50,000
|===
