---
title: Character Creation
weight: 14
prev: /docs/basic_concepts
next: /docs/character_backgrounds
---
:toc:

== Creating a character

Players follow these steps to create a new character.
Many concepts will become clearer in the next chapters.

. Roll on the <<tb_starting_ability_scores>> to determine an array of three scores and assign them randomly to the three abilities: Strength (STR), Agility (AGI), and Wits (WIT).
Roll a d3 to assign the highest score: 1) STR; 2) AGI; 3) WIT.
Roll a d2 to assign the middle score to one of the remaining abilities, skipping over the one which was already assigned.
Finally assign the lowest score to the last remaining ability.

. Determine your background by rolling on the <<tb_backgrounds>> table.
Read about it in the link:../character_backgrounds[Character Backgrounds] section.
Reroll if you get the same background as another Player.

. A few backgrounds increase two abilities by 1.
Adjust their scores if that's the case.

. You start with one or two skills granted by your background.
You can read what they do in the link:../skills[Skills] section.

. You start with health equal to your STR, 0 corruption, and 2 omens.
You also start with 0 mana unless your background is _wizard_, in which case you start with 1 mana.

. You start with d8 shillings (ʂ), the assets granted by your background, and the items and money you get by rolling once on each of the <<tb_starting_weapons>> and <<tb_starting_items>> tables.
Reroll if you get the same result as another Player on these tables.
You also share a single _candle_ and _flint & tinder_ with the other Player characters.
If you start with a _power scroll_ without a specified power, roll for it on the <<tb_sorcerous_powers>> or <<tb_sacred_powers>> tables.
You can read what your assets and powers do in the link:../assets[Assets] and link:../powers[Powers] section.

. Portray your character using words, drawings, or a combination of the two, as you prefer.
You can roll on the <<tb_appearance>>, <<tb_personality>>, and <<tb_reason_to_adventure>> tables if you need inspiration.

. Pick a suitable name, or roll on the <<tb_masculine_names>>, <<tb_feminine_names>>, and <<tb_last_names>> table to generate it randomly.


== Company relationships

After all characters have been created, describe how they know each other.
You can roll on the <<tb_relationships>> table if you need inspiration.
You don't have to do this for every possible pair of characters, but you should make sure that everyone is connected.
You can for example go around the table and define a connection for each pair of Players sitting next to each other, excluding the last pair.


== Character creation tables

include::gen/tb_starting_ability_scores.adoc[]

include::gen/tb_backgrounds.adoc[]

include::gen/tb_starting_weapons.adoc[]

include::gen/tb_starting_items.adoc[]

include::gen/tb_sacred_powers.adoc[]

include::gen/tb_sorcerous_powers.adoc[]

include::gen/tb_appearance.adoc[]

include::gen/tb_personality.adoc[]

include::gen/tb_reason_to_adventure.adoc[]

include::gen/tb_masculine_names.adoc[]

include::gen/tb_feminine_names.adoc[]

include::gen/tb_last_names.adoc[]

include::gen/tb_relationships.adoc[]
