---
title: Skills
weight: 24
prev: /docs/backgrounds
next: /docs/traits
---
:toc:

== Handling skills

Skills represent capabilities and expertise learnt by a character.
There are no degrees or values: a character either has a skill or doesn't.

The description of each skill lists the most common ways they can influence the game, but don't feel limited by this.
You should take skills into account any time it makes sense within the game narrative, providing advantages according to the GM's judgement.

One common effect is to allow characters to perform normally risky actions without a save, or to perform actions which would normally be impossible with a save.

++++
{{% details title="Example" closed="true" %}}

Sybilla (AGI 10) and Beatrice (AGI 8) want to climb a rocky cliff, which requires passing an AGI save.
Beatrice, however, has the _climbing_ skill, which means she is very good at climbing.
The GM rules that she succeeds automatically, without needing to roll.
Sybilla doesn't have the skill, so she must make a save.

Later they find themselves in a similar situation, but a torrential rain starts pouring, making the surface slippery.
The GM rules that it's practically impossible for most people to climb safely, so Sybilla can't even attempt to do it.
Since Beatrice has the _climbing_ skill, however, the GM allows her to attempt to do it with an AGI save.
Once she is on top, she rolls out a _rope ladder_ she had in her backpack to let Beatrice up.
The GM rules that climbing the ladder is trivial, even despite the rain, so Beatrice can just climb up without risks.

{{% /details %}}
++++

include::gen/ref_skill_list.adoc[]
