---
title: Abilities
weight: 15
prev: /rules/character_creation
next: /rules/careers
---
:toc:

== Abilities

The three abilities represent a character's basic proficiencies.
Each one is associated with a score ranging between 1 and 19.

* *Strength (STR)*.
Fortitude, might, physical power, toughness.

* *Agility (AGI)*.
Athleticism, dexterity, reflexes, swiftness.

* *Wits (WIT)*.
Awareness, charisma, cunning, willpower.


== Saves

Characters must make a save when threatened or when they attempt to do something challenging or risky, where the outcome is uncertain and failure has consequences.
They pass if they roll equal or less than the most relevant ability score on a d20, otherwise they fail and suffer some sort of penalty.

++++
{{% details title="Example" closed="true" %}}

Balthasar (AGI 7), Sybilla (AGI 10), and Theobald (AGI 6) want to climb a rocky cliff.
The GM adjudicates that this is a risky and challenging activity requiring an AGI save: whoever fails will fall and suffer d4 damage.

Theobald thinks it's too risky for him, and declares he would rather not attempt the climb.
Balthasar rolls a 6 on a d20: he passes and reaches the top of the climb unharmed.
Sybilla rolls a 13 on a d20: she isn't so lucky and falls, suffering damage and going back to where she started.

{{% /details %}}
++++


== Group saves

Sometimes, multiple characters must save against the same threat at once.
In this situation, the GM can ask to make a group save to speed up the game.
Roll the d20 only once and compare the result with each individual's ability score to see who passes and who fails.

++++
{{% details title="Example" closed="true" %}}

Balthasar (WIT 12), Sybilla (WIT 6), and Theobald (WIT 9) encounter a terrifying creature.
The GM asks them to pass a group WIT save to avoid being overwhelmed by fear.

One of the Players rolls a d20 and gets a 9: Balthasar and Theobald pass, but Sybilla fails and suffers the effects of fear.

{{% /details %}}
++++


== Contests

Characters who are directly competing against each other must make a contest to determine the winner.
All competing characters roll a d20 and subtract the result from the most relevant ability score.
They are then ranked from highest to lowest total.
Ties are broken by repeating the contest among the tying characters.

++++
{{% details title="Example" closed="true" %}}

Balthasar (STR 5), Sybilla (STR 8), and Theobald (STR 9) decide to engage in a friendly rock-throwing contest.
The GM decides that the winner will be decided with a STR contest.

Balthasar rolls a 6 on a d20, for a total of 5−6 = −1.
Sybilla rolls a 5, for a total of 8−5 = 3.
Theobald rolls a 20, for a total of 9−20 = −11.
The ranking is as follows: Sybilla first, then Balthasar, then Theobald.

{{% /details %}}
++++


