---
title: Adventuring Rules
weight: 70
prev: /rules/items_followers_and_services
next: /rules/combat_rules
---
:toc:


== Travel and exploration

When exploring a large section of the world or travelling, use a region-based map and track time with watches.
When exploring a site (a town, a dungeon...), use a sector or zone-based map and track time with stretches.
The game switches between these two modes as the company enters or leaves sites.

During each stretch or watch, the Players take turns performing an action.
Anything requiring a few minutes is a valid stretch action (moving across sectors, searching a zone, talking, fighting, etc.).
Anything requiring a few hours is a valid watch action (moving across regions, searching a sector or ar region, foraging, taking a daily rest, etc.).
Quicker actions can be performed at will, within reason.

After all Players have acted, the GM determines if they encounter someone or if anything relevant happens.
Then, a new stretch or watch begins.


== Perception

The GM describes what the Player characters can see, hear, smell, and feel when they enter a new area.
They should make sure to provide all necessary information for the Players to proceed through the scenario and make informed decisions: if in doubt, they should err on the side of providing too much information, rather than too little!
The Players should also ask clarifying questions to help the GM provide all necessary information.


== Secrets

Areas might contain concealed secrets.
A zone might contain traps, hidden treasures, secret passages, hiding characters, etc.
A sector might contain a concealed hut, a peculiar and hard to find shop, secret entrances, hidden encampments, etc.
A region might contain forgotten ruins, hidden caves, etc.

*Searching*.
Spending time to search an area automatically reveals all secrets within.
It takes a stretch to fully search a zone, and a watch to fully search a sector.
Searching a region also takes a watch, but only reveals a single secret within.

*Aimed search*.
If the Player characters look at exactly the right spot, they might detect secrets without performing a search, thus saving time.

*Passive detection*.
Secrets which aren't perfectly concealed can also be detective passively, without a search, when entering the area.
This requires passing a group WIT save, rolled secretly by the GM.


== Traps

Traps are treated as secrets, and thus can be detected by a careful search, an aimed search, or in some cases passive detection.
Even if a trap is perfectly concealed, the GM should mention some indirect clue about its existence, such as the remains of a previous, unfortunate adventurer: this gives the Players a chance to do something to investigate and avoid it.

Characters who notice a trap can stop in time before triggering it.
Characters who voluntarily trigger a detected trap can react to it when it makes sense, typically attempting an AGI save to dodge, while characters who trigger an undetected trap can't do anything to react.


== Knowledge

Skills and careers may grant knowledge in relevant fields.
For example, a character with the _medicine_ skill would be able to recognize the symptoms of a disease and know how it will develop, while a character with the _rat-catcher_ career would surely know a lot about those pesky rodents.
The GM should take this into account and provide additional information when appropriate.
The Players should also help the GM by reminding them when they think one of their skills or their career might grant them knowledge about the current situation.


== Languages

All Player characters can speak Common, plus any other languages granted by their skills.

*Common*.
The lingua franca of the Kingdom.
Pretty much everyone in the land can speak it.

*Classic*.
The language of scholars and clerics.
Sacred power scrolls are written in Classic.
Erudites from the Kingdom and nearby countries can speak it and use it to communicate with each other.

*Magick*.
The language of wizards and sorcery.
Profane power scrolls are written using this language.
It is rumoured to be the language spoken by demons.

*Other languages*.
People in different regions and countries speak a wide variety of languages and dialects.
Which ones actually matter for game purposes depend on the scenario or campaign at play.


== Literacy

Characters can't read, write, or perform anything but very simple calculations (likely with the aid of their fingers) unless they have a skill which grants them literacy: education is a privilege for the few!


== Encounters

When the company encounters a group of GM characters they can interact with, you should first set up the scene with an appropriate zone-based map, and then determine if the two groups are aware of each other.
Each side makes a group WIT save, and notices the other side if anyone in the group passes.

Groups which are being reckless (making noise, talking loudly, carrying a light in the dark, etc.) are automatically detected and can't detect the other group unless they are being reckless as well.
Groups which are well hidden and silent (for example laying in ambush in a thick forest) can't be detected with a WIT save, only with an active search, and automatically detect even cautious groups.

If only one group detects the other, they can choose how to approach the situation: parley, launch a surprise attack, go away, etc.
Otherwise, the Players declare what they want to do, while the GM secretly chooses for for the other group.
If at least one group wants to fight, a combat breaks out.
Conversely, a parley is only possible if both sides want to speak.

Dialogues are resolved with the GM and the Players describing (or, if you prefer, acting out) what their character say.
Saves might be triggered when the reaction of the GM characters to something the Players say is uncertain (see <<_diplomacy>> and <<_manipulation>>).
Fights are resolved as described in the link:../combat_rules[Combat Rules] chapter.
You can usually assume that resolving an encounter including a dialogue or a fight consumes a full stretch.


== Attitude

The GM can use the levels described in the <<tb_attitude>> table to express how other characters feel and behave towards the Player characters.
The GM can pick a suitable attitude, or roll to determine it randomly.
If the characters are particularly aggressive, roll 2d6 and keep the lower roll;
if they are peaceful, roll 2d6 and keep the higher roll;
otherwise, simply roll a d6.

.Attitude
[[tb_attitude]]
[options='header, unbreakable', cols="^2,<14"]
|===
|D6    |Attitude
|1     | *Hostile*. Actively tries to harm.
|2-3   | *Unfriendly*. Refuses to cooperate.
|4-5   | *Neutral*. Open to mutually beneficial deals.
|6     | *Friendly*. Open to help for little or nothing, but won't be taken advantage of.
|===


== Diplomacy

Characters who try to use diplomacy on others must pass a WIT save to determine if they are charismatic enough to succeed.

*Befriend*.
Perform a friendly activity (do a favour, give a present, buy some drinks, etc.) and pass a WIT save to improve a character's attitude towards you.
In case a big favour is made, the save is not required.

*Inspire*.
Appeal to someone's emotions and pass a WIT save to convince them to do something.
If the inspiration attempt is particularly effective or the incentives are very generous, the save is not required.

*Encourage*.
Spend a round to encourage an ally and pass a WIT save to clear their _frightened_ condition.

*Persuade*.
Provide convincing arguments and pass a WIT save to persuade a character of something they aren't inclined to believe, no matter if the truth or a lie.
If the arguments are particularly solid and supported by evidence, the save is not required.

*Bargain*.
Attempt to gain a better deal or some additional advantage.
If the proposed deal is unreasonable, the attempt always fails.


== Manipulation

Characters who are being manipulated must pass a WIT save to determine if they are wilful enough to resist.

*Distract*.
Perform a distracting activity (play music, start a conversation, make noise, etc.) to distract a character from something else.
The target can figure out they are being distracted with a WIT save unless the attempt is particularly effective.
Distracting someone in combat takes a round, and if successful, the target loses their next turn.

*Intimidate*.
Use threats and leverage to force a character to do or say something.
The target can attempt to resist by passing a WIT save unless it is quite evident that you are capable and willing to act on your threats and that they would have no chance to oppose you.
Intimidating someone in combat takes a round, and if successful, the target is _frightened_ by you.

*Taunt*.
Use insults and provocations and pass a WIT save to manipulate a character into act aggressively and impulsively.
The target can attempt to resist by passing a WIT save, unless your taunts are really pulling the right strings.
Taunting someone in combat takes a round, and if successful, the target can only spend their next turn trying to harm you.

*Torture*.
Torturing an imprisoned character takes a stretch of time and inflicts d6 direct damage.
The target, if still alive and conscious, must pass a WIT save or give up and talk.

It is important to stress that, even in combat, characters who wish to manipulate an enemy must describe their attempt, and the GM must evaluate if it's good enough to be effective and warrant a save.
Just shouting at someone won't intimidate them, but making a gruesome display of a fallen enemy might.


== Disguise

You can try to use clothes, makeup, and other method to disguise your appearance.
A _disguise kit_ contains all that's necessary.
You can only attempt to look different from your usual self, not to look like another specific person, unless you already look quite similar.
Other characters can passively notice that something is off about you by passing a WIT save, and close examination will always reveal the disguise.


== Skills in dialogues

Some skills (_blather_, _charm_, _intimidate_, _leadership_) grant proficiency when using certain diplomatic or manipulation approaches.
However, other skills can also provide an advantage when it makes sense.
For example, the _erudition_ skill might be useful when trying to persuade someone about historical events, while the _music_ skill might come in handy when attempting to distract someone with a musical performance.


== Stealing

Stealing an item with bulk ½ from a nearby character requires passing an AGI save to avoid detection.
Stealing larger items is normally impossible.
Approaching the target without being noticed might require an additional AGI save to sneak without being detected.


== Trading

Goods can be purchased in exchange for something of at least equal value.
Characters with the _bargain_ skill buy at half price, unless the seller also has the skill.
Professional merchants further reduce price by half, as they aim to make a profit by reselling the goods.
This means that they will buy at ¼ the value, or at half the value from someone with the _bargain_ skill.

While in a settlement, characters can spend a watch to buy and sell any number of items in the local market.
It is assumed they interact with professional merchants with the _bargain_ skill.
Looking for a good buyer who's willing to pay full price for a specific item takes a full watch and requires passing a WIT save.

Most people won't trade clearly illegal or stolen goods.
Those willing to do so will sell at double price and buy at half price.
Finding such people in a settlement takes a watch and requires passing a WIT save.


== Gathering rumours

Player characters can spend a watch in a settlement to talk with the locals and hear interesting rumours.
The GM decides what they hear, and it might not necessarily be true.


== Playing games

A game is resolved as an ability contest, usually WIT or AGI.
Luck-based games are resolved with a d20 roll, with the winner being whoever rolls lowest.

Cheating requires declaring how the attempt is made and passing a WIT save to avoid detection.
The GM should roll the contest d20 secretly for GM characters to avoid giving away if they are cheating: if they play honestly it is their contest roll, if they are cheating it is their WIT save to avoid detection.


== Special movement

*Sprint*.
Move at double speed (usually 4 zones in a round instead of 2) across open terrain.
If the terrain is rough or presents obstacles (mud, a furnished room, thick vegetation, etc.) passing an AGI save is required to avoid tripping and suffering d4 direct damage.
It is impossible to sprint on very rough terrain (very slippery, rocky and uneven, very cramped, etc.).

*Sneak*.
Move silently and behind cover.
The character stays undetected if they pass an AGI save.
Trivial in loud and dark places, impossible on very noisy surfaces and in plain view.

*Balance*.
When moving on difficult ground (slippery, uneven, narrow, etc.), characters must pass an AGI save or trip.
Characters who trip suffer d4 direct damage and can't move further until the next round.
Impossible on very difficult ground (for example slippery _and_ narrow).
Attacks made while balancing are impaired.

*Leap*.
Pass an AGI save to leap across a significant obstacle or gap (4 metres with a running start, 2 metres otherwise).
Trivial for tiny gaps (2 metres or less with a running start, 1 metre otherwise), impossible for very large gaps.
Attacks made while leaping are impaired.

*Climb*.
When climbing a challenging surface, characters must pass an AGI save or fall.
They must make the save when they start climbing and at the start of each round.
Trivial on easy surfaces (such as ladders), impossible on smooth surfaces (such as walls).
Attacks made while climbing are impaired, and at least one hand must be used to keep hold of the surface.

*Swim*.
When swimming in turbulent waters or while carrying a total bulk greater than 2, characters must pass an AGI save or start drowning.
They must make the save when they enter the waters, and at the start of each round.
While drowning, they can't do anything and might suffocate (see <<_suffocating>>).
Attacks made while in water are impaired.

Characters can't make special movements for more than a stretch consecutively.
It isn't possible to combine special movements unless the character is proficient in one of them.
For example, characters can't sprint while climbing, or sneak while swimming.


== Navigating the wilderness

Moving across sectors or regions without following a clear path (a road, a river, etc.) bears the risk of getting lost, wasting time to find the right way again.
To represent this in a simple way, movement speed is reduced to ¼ in such a situation, meaning that the typical movement speed is half a sector or region per stretch or watch.


== Bad weather

Movement speed is halved when travelling across sectors and regions under extremely bad weather (torrential rain, scorching heat, etc.).
It is also impossible to take a daily rest in the wilderness, unless proper shelter is found in the vicinity by spending a watch and passing a WIT save.


== Locks

Locked doors and chests can be opened using _lockpicks_ or a _crowbar_.
This takes a watch and requires passing a WIT or STR save respectively.
Locked or blocked old doors can also be bashed open without tools by passing a STR save.
Finally, doors can be destroyed by attacking them with suitable weapons.
A typical wooden door has 8 health and 1 armour and takes impaired damage, unless a weapon or tool which would particularly effective is used.


== Falling

Characters who fall by 2 metres or more suffer d4 direct damage for each full 2 metres they traverse.
They can attempt to cushion the fall and land gracefully by passing an AGI save, in which case the effective falling distance is reduced by 2 metres.


== Suffocating

Characters can hold their breath for 4 rounds.
Afterwards they must pass a STR save at the end of each round or pass out, becoming _incapacitated_ until the end of the stretch.
They die if they fail another save to resist suffocation while _incapacitated_.


== Elemental damage

*Cold and heat* inflict direct damage.
Characters in a freezing or scorching hot environment suffer d4 impaired cold or heat damage at the end of each stretch.

*Fire* inflicts direct damage, enhanced against targets made of or covered in flammable substances.
Characters who enter or start their round in a zone which is currently on fire suffer d6 fire damage.

*Lightning* inflicts direct damage, enhanced against targets carrying significant amounts of metal.
Lightning attacks directed at wet zones behave as blast attacks.


== Fear & terror

Characters exposed to frightening or terrifying creatures and events must pass a WIT save or become respectively _frightened_ or _terrified_ until the end of the stretch.
Repeat the WIT save at the start of each stretch, as long as the source of fear persists.
When multiple characters are affected at once, make a group save.

_Frightened_ characters can't approach the source of their fear.
_Terrified_ characters must run away, and if they can't, they cower in terror and can't do anything else.

Some effects let characters ignore fear and treat terror as fear.
Two such effects can stack together to let characters ignore terror as well.


== Poison

Characters can resist the first dose of poison they are exposed to each stretch by passing a STR save.
If exposed to any poison again during the same stretch, the effect is automatic.
Every type of poison has a delivery method and an effect.

*Delivery methods*:

* *Bloodstream*.
The poison must enter the victim's blood.
You can coat a sharp weapon or item with the poison in a round.
The dose is delivered on the first attack inflicting at least 1 damage, after reduction.

* *Ingestion*.
The poison must be ingested.
If mixed with food or drinks, characters can detect that something is wrong before consuming it by passing a WIT save.
However, if the food or drink have a very strong taste, it might be impossible to detect the poison.

*Effects*:

* *Damaging*.
Victims must take an _antidote_ by the end of the stretch or suffer d12 direct damage.

* *Corrupting*.
Victims must take an _antidote_ by the end of the stretch or suffer 4 corruption.

* *Lethal*.
Victims must take an _antidote_ by the end of the stretch or die.

* *Paralysing*.
Victims are _incapacitated_ until the end of the stretch.
The effect ends earlier if they take an _antidote_.

* *Soporific*.
Victims are _incapacitated_ until the end of the watch.
The effect ends earlier if they suffer damage or take an _antidote_.


== Drugs

Drugs count as poison and their effect can be resisted in the same way.
Additionally, if the drug has effect, the character must pass a WIT save or become _addicted_ to it.

Addicted characters must consume the drug each time they take a daily rest or temporarily reduce WIT by 1.
After a full rest, they must consume 8 units of the drug or temporarily reduce WIT by 1 for each missing unit.


== Disease

Characters exposed to a disease, including spending time close to an infected person, become _sick_.
_Sick_ characters must make a recovery save based on STR at the end of each day.
They recover after accumulating 2 successes in total, but they temporarily reduce STR, AGI, and WIT by d4 each time they fail, as the symptoms of the disease worsen.
Characters who do get _sick_ and recover develop a lasting immunity and can't suffer from the same disease again.

* *Influence*.
A bad flu, which follows no special rules.
Symptoms include fever, coughing, sneezing, sore throat, and digestive issues.
Being a seasonal disease with many variants, immunity only lasts for a limited time.

* *Black gangrene*.
Symptoms include high fever and blackening of the feet.
If a victim fails a recovery roll for the second time, their feet start decomposing.
They must be surgically amputated within a day (using _surgical tools_ and passing a WIT save), or the victim dies.

* *Bloodburn*.
Symptoms include strong headache, blurry visions, and the insatiable need to spill blood.
After failing a recovery save, victims are also _frenzied_ until the next recovery save, and will attack anybody indiscriminately.

* *Bloody flu*.
Similar to a normal influence, it follows no special rules.
However, people are irrationally terrified by it and will avoid those infected like the plague.

* *Demon pox*.
Symptoms include hallucinations and weird buboes, constantly changing shape and colour and slowly moving across the body.
Victims who fail a recovery roll also suffer 2 corruption.

* *Digworm*.
A parasite digging into the victim's skin and sucking their blood.
Symptoms include fever, weakness, and constant hunger.
Healing naturally via recovery saves isn't possible, but the parasite can be surgically removed (using _surgical tools_ and passing a WIT save).
Recovery saves must still be made to determine if the disease causes ability reduction.
Not contagious.
Immunity against it isn't developed after recovery.

* *Greater rot*.
Symptoms are abhorrent and often leave the victim permanently debilitated: rotting flesh, pulsating buboes, vomiting, diarrhoea, cough, and high fever.
Victims who fail a recover roll reduce their ability scores as usual, but one point of reduction for each ability is permanent rather than temporary.
_Cures_ don't work, only natural recovery or magic powers can help.

* *Plague*.
Symptoms include fever and large buboes.
Healing requires 4 successful recovery saves.

* *Weeping sores*.
Symptoms include painful sores appearing all over the body.
On a failed recovery roll, STR and AGI are reduced by d6 instead of d4, but WIT isn't reduced.


== Crafting

Everyone can craft crude, improvised items in a watch by using appropriate tools, consuming appropriate raw materials, and passing a save (usually STR or WIT).
Such items always have a considerable flaw or disadvantage, as decided by the GM, typically the _fragile_ keyword.
Examples include: a club with sharp nails, a spear with a tip made of a beast's fang, a crude shelter to rest in the wilderness, etc.

A few skills grant the ability to craft high-quality items of certain types.
Crafting an item takes a watch and requires a suitable workshop or tools, as indicated in the skill description.
No save is required unless trying to create a _master-crafted_ or _robust_ version of the item.
Consumable items can be crafted in batches of 2.

Raw materials cost ¼ the value of the item.
If the GM allows, they might sometimes be gathered the area, typically by spending a stretch or a watch.


== Training animals

Characters can train a domesticated animal as a full rest activity.
The trainer must make a WIT save: if they pass, the animal was trained successfully; if they fail, they are hurt and suffer an injury after the rest.
Each individual animal can receive at most two forms of training.

* *Mount*.
The animal will accept a rider as a mount.

* *Labour*.
The animal will pull carts, work in a mill, etc.

* *Fight*.
The animal will take active part to fights and can obey fight-related commands.
Untrained animals might still fight based on their instincts, however they won't follow orders unless trained.

* *Hunt*.
When foraging, gain an additional _ration_.

* *Track*.
Can automatically follow tracks, for example when hunting.

* *Tricks*.
Can perform tricks, such as jumping through hoops, balancing items on the nose, etc.

Proficient characters can attempt to train wild animals as well.
Before being trained to do anything else, wild animals must be tamed, which requires an additional training session.


== Befriending animals

It is possible to befriend a domesticated animal by offering some food and passing a WIT save.
On a fail, the animal might run away or turn hostile.
A befriended animal follows the character for a watch or until they move too far from their territory.
It is possible to be accompanied by a single befriended animal at a time.
Befriending a wild animal is impossible unless the character is proficient.


== Mounts

Characters can ride a trained mount with a _saddle_.
Riding in quiet situations is trivial, but the rider must make an AGI save when the mount sprints, leaps, dodges an attack, is scared, and in other dangerous situations (as a general guideline, every time the mount makes an AGI save).
If they fail, they fall from the mount and suffer d4 direct damage.


== Carts

Carts must be pulled by one or more characters, typically trained beasts of burden, and driven by a character.
They move at the speed of the characters pulling them.
The driver must make a STR save when the cart sprints, when the beasts pulling it are scared, and in other dangerous situations.
If they fail, the cart crashes and topples: the cart and all passengers suffer d4 direct damage.


== Boats

All boats can be rowed, and sailing boats can sailed by a crew of characters with the _river lore_ skill.
One character must act as the driver.
Boats move 4 areas per time unit if moving with the current or wind, and by 2 areas per time unit otherwise.
If manned by fewer characters than the amount indicated in the description, speed is reduced accordingly.
The driver must make a STR save (while rowing) or WIT save (while sailing) in dangerous situation, for example on turbulent waters.
On a fail the boat crashes or topples: the boat and all passengers suffer d4 direct damage.


== Size categories

Characters belong to one size category: tiny, small, medium, large, or massive.
Humans and other similarly-sized characters are medium.

*Bulk and carry limit*.
½ if tiny, 2 if small, 8 if medium, 32 if large, 128 if massive.

*Zone occupancy*.
Keep track of zone occupancy separately for characters of different size.
A typical zone can hold 128 tiny, 32 small, 8 medium, and 2 large characters.
Massive characters can only fit inside large and open zones (fitting 16 medium characters).

*Saves*.
Larger characters automatically win STR saves and contests against smaller characters, and automatically lose AGI or WIT contests when their size is a disadvantage.

++++
{{% details title="Example" closed="true" %}}

A troll is a larger creature with STR 12.
Its bulk and carry limit are 32 instead of 8.
It would automatically win any STR save and contest against humans and other medium-sized or smaller creatures.

{{% /details %}}
++++
