---
title: Bestiary
weight: 130
prev: /rules/magic_rules
next: /rules/gm_tips
---
:toc:

== Folks

All humanoid kins who inhabit the world, besides humans.
They form their own communities and are a rare sight within the Kingdom.

The profiles show the average ability scores, which can vary just like for human characters.
The minimum score is the given one minus 3 (minimum 1), and the maximum score is the given one plus 7 (maximum 19).
No skills or assets are shown, as those depend on the character's career just like human characters.

include::gen/ref_folks.adoc[]


== Reanimated corpses

Dead bodies dragged back to unlife by vile sorcery.
A reanimated corpse obeys the sorcerer who created it, without question.
You can build the profile of a reanimated corpse starting from any creature using these rules:

* Halve AGI and set WIT to 2.

* Lose all skills.

* Acquire the _frightening_ (_terrifying_ if already _frightening_), _immunity (corruption, disease, poison)_, _mindless_, and _undead_ traits.

include::gen/ref_reanimated_corpses.adoc[]


== Demons

Demons are the product of pure chaos, denizens of an alternate dimension.
Each one is different and unique in its own way, and can never truly be destroyed, only banished back to where it came from.

include::gen/ref_demons.adoc[]


== Monsters

Mighty and ferocious creatures of legend.
Few survive to tell the tale of an encounter with such forces of nature!

include::gen/ref_monsters.adoc[]


== Domesticated animals

Animals which have been bred and selected to work with humans.
They are typically docile and obedient, even though individual animals which have received no training might still be aggressive or distrustful.

include::gen/ref_domesticated_animals.adoc[]


== Wild animals

Animals found in the wild.
They can only act as followers if first tamed by someone with the right skill set.

include::gen/ref_wild_animals.adoc[]
