---
title: Character Categories
weight: 160
prev: /rules/powers
next: /rules/mounts_and_vehicles
---
:toc:

== Categories

Characters are categorized by kind, intelligence, and size.

* *Kind*.
The character's basic nature: _creature_, _construct_, _demon_, or _undead_.

* *Intelligence*.
The character's level of intelligence: _human_, _animal_, or _mindless_.

* *Size*.
How large the character is: _tiny_, _small_, _medium-sized_, _large_, _massive_.

Humans are medium-sized creatures with human intelligence.


include::gen/ref_kind.adoc[]


== Intelligence

* *Human intelligence*.
High level of intelligence.
Can speak, learn complex skills, reason, use tools, etc.

* *Animal intelligence*.
Low level of intelligence.
Can communicate with members of the same species in a limited way, learn simple skills and tricks, etc.
Mostly behaves according to instinct.

* *Mindless*.
No actual intelligence, such as an automaton or a flesh puppet.
Behaves in a very restricted way, following some sort of '`programming`'.
Is immune to mind control, fear, and other mental effects.


== Size

* Bulk, carry limit, health, damage inflicted, and armour value depend on size as shown in the <<tb_size_and_properties>> table.
Massive characters can also perform melee attacks within range 1.

* Tiny characters count as 1/16 towards zone occupancy, small characters as ¼, large characters as 4, and massive characters as 16.
If you are playing with a grid, large characters occupy 2×2 squares, massive characters occupy 4×4 squares, and small and tiny characters occupy a fraction of a square.

* Larger characters can trample smaller characters while moving, forcing them to move into a nearby zone or border or suffer d4 damage.

* All characters can make melee sweep attacks.
The attack gains the _blast_ keyword, but only affects smaller targets and inflicts half damage.

* Blast attacks can be directed at a single large or massive character.
The attack loses the benefit of the _blast_ keyword but inflicts double damage.

* Larger characters can grab smaller character with only one hand or another appendage.
They are free to perform any action without letting the grabbed character go.
Instead of shoving the character, they can throw them within range 2, inflicting d4 direct damage.

* Larger characters automatically win STR saves and contests against smaller characters.
Size might also come into play in other types of saves.
For example, it might be trivial for a smaller character to sneak behind a larger one, and the opposite might be impossible.

.Size and properties
[[tb_size_and_properties]]
[options='header, unbreakable', cols="^1,^1,^1,^1,^1,^1"]
|===
|Size      |Bulk |Carry limit |Health    |Damage inflicted   |Armour value
|Tiny      |0.5  |0.5         |STR÷4     |÷4                 |×1
|Small     |2    |2           |STR÷2     |÷2                 |×1
|Medium    |8    |8           |STR       |Unmodified         |Unmodified
|Large     |32   |32          |STR×2     |×2                 |×2
|Massive   |128  |128         |STR×4     |×4 (range 1)       |×4
|===
