---
title: Character Creation
weight: 14
prev: /rules/basic_concepts
next: /rules/abilities
---
:toc:

== Creating a random character

By default, characters are created randomly.
You can follow the process below step by step or use the online link:../../character_generator[Character Generator].
If you wish to change some parts of your rolled character (abilities, career...) discuss with the GM.

. *Abilities*.
Roll on the <<tb_starting_ability_scores>> to determine an array of three scores and assign them randomly to the three abilities: Strength (STR), Agility (AGI), and Wits (WIT).

** Roll a d3 to assign the highest score: 1) STR; 2) AGI; 3) WIT.

** Roll a d2 to assign the middle score to one of the remaining abilities, skipping over the one which was already assigned.

** Finally, assign the lowest score to the last remaining ability.

. *Career*.
Determine your past career by rolling on the <<tb_careers>> table.
Check its description in the link:../careers[Careers] chapter.
Re-roll if you get the same career as another Player.

. *Skills*. You start with two skills granted by your career.
Check their description in the link:../skills[Skills] chapter.

. *Assets*.
You start with d8 shillings (ʂ), the items and followers granted by your career, and the items and shillings you get by rolling once on each of the <<tb_starting_weapons>> and <<tb_starting_items>> tables.
If you start with one or more sacred or profane _power scrolls_, roll on the <<tb_sacred_powers>> or <<tb_profane_powers>> tables respectively to determine what power they contain.
Re-roll if you get the same result as another Player on any table.

. *Secondary properties*.
You start with health equal to your STR (plus 2 if you have the _tough_ skill), 0 corruption, 0 mana, and 2 omens.
Your armour value depends on your starting items.

. *Name and description*.
Name and portray your character using words, drawings, or a combination of the two, as you prefer.
You can roll on the <<tb_masculine_first_names>>, <<tb_feminine_first_names>>, <<tb_last_names>>, <<tb_appearance>>, <<tb_personality>>, and <<tb_reasons_to_adventure>> tables if you need inspiration.

++++
{{% details title="Example" closed="true" %}}

David is creating a new character.

1. He rolls 7 on a d12 for the abilities scores: 11, 7, and 6.
He rolls a d3 to assign the highest score (11) and gets a 2 (AGI).
Furthermore, he rolls a d2 to assign the middle score (7) and gets a 2 again (WIT in this case, skipping over AGI).
His character's starting abilities are therefore: **STR** 6, **AGI** 11, **WIT** 7.

2. He rolls a 4 on a d4 and a 10 on a d12 for the career: _soldier_.

3. His career grants him the _cleave_ and _skilled blow_ skills.

4. He starts with the following assets:

    * He rolls 1 on a d8 for starting money: 1ʂ.

    * His career provides _clothes_ and a _halberd_.

    * He rolls 1 on a d2 and 5 on a d12 for his starting weapon: a _boat hook_ plus 4ʂ.

    * He rolls 2 on a d2 and 1 on a d12 for his starting item: one dose of _flash powder_.

5. He notes down his secondary properties: health is 6 (equal to STR), corruption is 0, omens are 2, mana is 0, and armour value is 0.

6. He finally describes and names his character.

{{% /details %}}
++++


== Company relationships

After all characters have been created, describe how they know each other.
You can roll on the <<tb_relationships>> table if you need inspiration.
You don't have to do this for every possible pair of characters, but you should make sure that everyone is connected.
For example, you can go around the table and define a connection for each pair of Players sitting next to each other, excluding the last pair.


== Character creation tables

.Starting ability scores
[[tb_starting_ability_scores]]
[options='header, unbreakable', cols="^1,^4,^1,^4,^1,^4"]
|===
|D12 |Scores
|D12 |Scores
|D12 |Scores
|1 |8, 8, 8
|2 |9, 8, 7
|3 |9, 9, 6
|4 |10, 7, 7
|5 |10, 8, 6
|6 |10, 9, 5
|7 |11, 7, 6
|8 |11, 8, 5
|9 |12, 6, 6
|10 |12, 7, 5
|11 |13, 6, 5
|12 |14, 5, 5
|===

include::gen/tb_careers.adoc[]

include::gen/tb_starting_weapons.adoc[]

include::gen/tb_starting_items.adoc[]

include::gen/tb_sacred_powers.adoc[]

include::gen/tb_profane_powers.adoc[]

include::gen/tb_appearance.adoc[]

include::gen/tb_personality.adoc[]

include::gen/tb_reasons_to_adventure.adoc[]

include::gen/tb_masculine_first_names.adoc[]

include::gen/tb_feminine_first_names.adoc[]

include::gen/tb_last_names.adoc[]

include::gen/tb_relationships.adoc[]
