---
title: Encounters
weight: 130
prev: /rules/hazards
next: /rules/combat
---
:toc:

== Attitude

The GM can use the following levels to express the attitude that other characters have towards the Player characters:

* *Hostile* characters actively try to harm the Player characters.

* *Unfriendly* characters refuse to cooperate with the Player characters, but won't go out of their way to harm them.

* *Neutral* characters just do what's best for them.
They are open to mutually beneficial deals.

* *Friendly* characters are open to help and do favours.
They will still expect to get something in return at some point.

* *Infatuated* characters will be extremely friendly towards the Player characters, often doing favours in exchange for little or nothing.
They still won't do something which will harm them, and if they start feeling they are taken advantage of their attitude might worsen.


== Diplomacy

Characters who try to use diplomacy on others must pass a WIT save to determine if they are charismatic enough to succeed.
The following are typical diplomacy attempts:

* *Befriend*.
Perform a friendly activity (do a favour, give a present, buy some drinks, etc.) and pass a WIT save to improve a character's attitude towards you.
In case a big favour is made the save is not required.

* *Inspire*.
Appeal to someone's emotions or provide them with incentives (payments, favours, etc.) and pass a WIT save to convince them to do something.
If the inspiration attempt is particularly effective or the incentives are very generous, the save is not required.

* *Persuade*.
Provide convincing arguments and pass a WIT save to persuade a character of something they aren't inclined to believe, no matter if the truth or a lie.
If the arguments are particularly solid and supported by evidence the save is not required.


== Manipulation

Characters who are being manipulated must pass a WIT save to determine if they are wilful enough to resist.
The following are typical manipulation attempts:

* *Distract*.
Perform a distracting activity (play music, start a conversation, make noise, etc.) to distract a character from something else.
The target can figure out they are being distracted with a WIT save unless the attempt is particularly effective.
Distracting someone in combat is a main action, and if successful the target loses their next turn.

* *Intimidate*.
Use threats and leverage to force a character to do or say something.
The target can attempt to resist by passing a WIT save unless it is quite evident that you are capable and willing to act on your threats and that they would have no chance to oppose you.
Intimidating someone in combat is a main action, and if successful the target is _frightened_ by you.

* *Taunt*.
Use insults and provocations and pass a WIT save to manipulate a character into act aggressively and impulsively.
The target can attempt to resist by passing a WIT save unless your taunts are really pulling the right strings.
Taunting someone in combat is a main action, and if successful the target can only spend their next turn trying to harm you.

* *Torture*.
Torturing an imprisoned character takes a stretch of time and inflicts d6 direct damage.
The target, if still alive and conscious, must pass a WIT save or give up and talk.


== Languages

* _Common_ is the lingua franca of the Kingdom.
Pretty much everyone in the land can speak it, with more or less atrocious accent.

* _Classic_ is the language of scholars and the Church.
Erudites from the Kingdom and other countries can speak it and use it communicate.
Sacred power scrolls are written in Classic.

* _Magick_ is the language of sorcery.
It is too cryptic and esoteric to be used to communicate effectively.
Profane power scrolls are written using this language.

* Different regions, countries, and people speak a variety of languages.
Which ones matter depend on the campaign setting.

All Player characters can speak Common plus other languages if granted by their skills.
Characters can't read, write, or perform anything but very simple calculations unless they have a skill which grants this ability: education is a privilege for the few!


== Stealing

Stealing an item with bulk ½ from a nearby character requires passing an AGI save to avoid detection.
Stealing larger items is normally impossible.
Approaching the target without being noticed might require an additional AGI save to sneak without being detected.


== Trading

Goods can be purchased in exchange of something of at least equal value.
The value of items is indicated on their profile.
The value of less tangible assets, such as favours and peculiar services, must be adjudicated by the GM.

* If the buyer has the _bargain_ skill and the seller doesn't, goods are sold at half price.
You can assume that most GM characters willing to buy most common gear and goods do have this skill!

* Professional merchants want to make a profit and will only buy at half value.

* Second hand items, such as most gear owned or looted by the Player characters, are worth half.

* Damaged items are worth nothing.

* Goods in high demand are worth double or quadruple, while those in low demand are worth half or a quarter.

* Illegal goods are sold at one quarter of their value and bought at four times their value, and most people will refuse to handle them.


== Gathering rumours

Player characters can spend a watch in a settlement to talk with the locals and hear interesting rumours.
The GM decides what they hear, and it might not necessarily be true.


== Playing games

A game is resolved as an ability contest, usually WIT or AGI.
Luck-based games are resolved with a d20 roll, with the winner being whoever rolls lowest.

Cheating requires declaring how the attempt is made and passing a WIT save to avoid detection.
The GM should roll the contest d20 secretly for GM characters to avoid giving away if they are cheating: if they play honestly it is their contest roll, if they are cheating it is their WIT save to avoid detection.
