---
title: Followers
weight: 81
prev: /rules/items
next: /rules/services
---
:toc:



== Retainers

Followers with human intelligence act as retainers, joining the party due to common interests or in exchange for payment.
They pretty much behave like Player characters, but they might refuse to perform specific tasks unless they were agreed as part of their responsibilities.


== Animal followers

Followers with animal intelligence behave according to their nature.
If trained, they might be able to obey simple orders and perform specific tasks, such as carrying a rider, pulling carts, following trails, performing tricks, etc.
Animals will avoid combat and other dangerous situations unless they are natural predators or have been trained to fight.


== Training animals

Animals can be trained to become followers.
It is possible to tame a single captive animal during a full rest.
Training a domesticated animal (horses, dogs...) requires passing a WIT save: on a fail the animal wasn't trained successfully, and the trainer must roll on the link:../health#injuries[Injuries] table at the end of the rest.
Training a wild animal (wolves, lions...) is impossible unless the trainer is proficient.


== Befriending animals

It is possible to befriend a domesticated animal by offering some food and passing a WIT save.
A befriended animal follows the character for a watch or until they move too far from their territory.
It is possible to be accompanied by a single befriended animal at a time.
Befriending a wild animal is impossible unless the character is proficient.


== Controlling followers

Players control followers as their own character, assuming they are giving them orders.
The GM however ultimately decides if and how they do what they are asked.
Followers will always refuse to do something clearly harmful to themselves.
In situations where their loyalty is put into question, the character who is leading them must pass a WIT save to keep their allegiance.

== Cost of followers

* *Animal* (*).
Check the link:../bestiary[Bestiary] section for profiles and values in shillings.
Wild animals cost double if trained to obey and follow commands.
Docile animals cost double if trained to fight.
Animals trained for hunting cost double and grant an additional _ration_ while foraging.
Animals trained to perform tricks (jumping through hoops, balancing stuff on the nose, etc.) cost double.

* *Labourer* (16ʂ).
Hired for a day to carry stuff and perform menial labour.
Won't fight or provide other services.

* *Expert* (32ʂ).
Hired for a day to provide some form of expertise (guide, knowledge, healing, etc.)
Won't fight, carry stuff, or perform menial labour.

* *Mercenary* (64ʂ).
Hired for a day to fight.
Won't carry stuff, perform menial labour, or provide services other than fighting.
