---
title: Followers
weight: 81
prev: /rules/items
next: /rules/services
---
:toc:



== Retainers

Followers with human intelligence act as retainers, joining the party due to common interests or in exchange for payment.
They pretty much behave like Player characters, but they might refuse to perform specific tasks unless they were agreed as part of their responsibilities.


== Animal followers

Followers with animal intelligence behave according to their nature.
If trained, they might be able to obey simple orders and perform specific tasks, such as carrying a rider, pulling carts, following trails, performing tricks, etc.
Animals will avoid combat and other dangerous situations unless they are natural predators or have been trained to fight.


== Training animals

Once per full rest, it is possible to train a domesticated animal in one of the following ways.
The trainer must pass a WIT save, otherwise the training is not successful and the trainer is hurt and suffers an injury after the rest.

* *Fight*.
The animal will take active part to fights and can obey fight-related commands.
Untrained animals might still fight based on their instincts, however they won't follow orders unless trained.

* *Hunt*.
When foraging, gain an additional _ration_.

* *Track*.
Can automatically follow tracks, for example when hunting.

* *Tricks*.
Can perform tricks, such as jumping through hoops, balancing items on the nose...

Proficient characters can train domesticated animals without a save, and can attempt to train wild animals with a save.
Before being trained to do anything else, wild animals must be tamed, which counts as an additional training session.


== Befriending animals

It is possible to befriend a domesticated animal by offering some food and passing a WIT save.
A befriended animal follows the character for a watch or until they move too far from their territory.
It is possible to be accompanied by a single befriended animal at a time.
Befriending a wild animal is impossible unless the character is proficient.


== Controlling followers

Players control followers as their own character, assuming they are giving them orders.
The GM however ultimately decides if and how they do what they are asked.
Followers will always refuse to do something clearly harmful to themselves.
In situations where their loyalty is put into question, the character who is leading them must pass a WIT save to keep their allegiance.


== Cost of followers

* *Animal* (*).
Check the link:../bestiary[Bestiary] section for profiles and values in shillings.
For each type of training it has received, double the cost.

* *Labourer* (16ʂ).
Hired for a day to carry stuff and perform menial labour.
Won't fight or provide other services.

* *Expert* (32ʂ).
Hired for a day to provide some form of expertise (guide, knowledge, healing, etc.)
Won't fight, carry stuff, or perform menial labour.

* *Mercenary* (64ʂ).
Hired for a day to fight.
Won't carry stuff, perform menial labour, or provide services other than fighting.
