---
title: GM Tips
weight: 140
prev: /rules/bestiary
---
:toc:


== Creating characters

Here are a few tips to create GM characters.

* *Generic characters*.
Pick a career and assume all abilities are average (8 each for humans).
That's all you need!

* *Important characters*.
Simply decide their ability scores, abilities, and equipment.
You can also assign 1 or 2 omens to very important characters.

* *Monsters and other creatures*.
You can use the following process, but don't feel constrained by it.

.. Pick the size: tiny (mouse-sized), small (dog-sized), medium (human-sized), large (elephant-sized), massive (whale-sized).

.. Assign STR: 4 if tiny; 4 or 8 if small; 4, 8, 12, 16 of medium; 12 or 16 if large; 16 if massive.

.. Assign AGI: 4 if clumsy, 8 if average, 12 if agile.
Add 4 if able to fly.

.. Assign STR: 4 if slow-witted, 8 if average, 12 if attentive, 16 if extremely cunning.

.. Assign traits and skills as you see fit.
Feel free to create new ones if necessary!
Particularly common trait are: _sturdy_ (for quadrupeds), _fast_ (for fast-moving animals), _flyer_, _beast_ or _undead_ or _demon_ (the kind of creature).

.. Assign natural weapons: usually inflict d4 or d6 damage.

.. Assign natural armour: 1 for thick skin or scales, 2 for particularly strong protection.


== Grids

You can use a square grid instead of zones to keep track of where the characters are in combat or when exploring a site.
A square represents an area of 2 metres by 2 metres and can be occupied by a single medium-sized character.
Large characters occupy 2×2 squares, massive characters occupy 4×4 squares, and small and tiny characters occupy a fraction of a square.

Multiply by 2 to convert distances and ranges from zones to squares.
For example, a range of 2 zones would correspond to 4 squares.
Anything affecting a whole zone, such as blast attacks, affects a 3 squares by 3 squares area instead.


== Experience for money

One way to award advancements is to use the experience for money method.
Player characters earn experience points by spending money, at a rate of one experience point per shilling, and advance at certain thresholds.
Money spent in this way is lost and can't be retrieved in any way: it is stashed away for retirement, wasted carousing, donated to a good cause, etc.
The <<tb_experience_and_advancements>> table shows the amount of experience point required to reach certain advancements, but feel free to modify it based on your requirements.

.Experience and advancements
[[tb_experience_and_advancements]]
[options='header, unbreakable', cols="^2,^4,^2,^4"]
|===
|Advancement |Experience required
|Advancement |Experience required
|1   |125
|2   |250
|3   |500
|4   |1,000
|5   |2,000
|6   |4,000
|7   |8,000
|8   |16,000
|9   |32,000
|10  |64,000
|11+  3+|Add 32,000
|===


== Combat initiative

You can use this variant if you would like AGI to influence the order in which characters act during the round, and you don't mind a bit of extra complexity.

At the beginning of each round, the GM openly rolls a d20.
The result is the "`fast action threshold`".
You can leave the d20 on the table as a reminder of this value.
The round is divided in two phases: fast action and slow action.

* During the fast action phase, only characters whose AGI matches or exceeds the fast action threshold can take their turn.

* During the slow action phase, all characters who haven't acted yet (either because their AGI is too low or due to early passing) can take their turn.

Each phase ends when all factions pass consecutively, as per the usual rules.
Characters can react during any phase, no matter what their AGI score is.

++++
{{% details title="Example" closed="true" %}}

Wolfgang (AGI 9), Sybilla (AGI 10), and Theobald (AGI 7) are fighting against two bandits (AGI 8) and their leader (AGI 10).
The Players have the initiative.

The GM rolls a d20 to determine the fast action threshold: the result is 9.
During the fast actions phase, only Wolfgang, Sybilla, and the bandit leader can act.
Theobald and the two bandits can't, because their AGI is lower than 9.
The round plays out in this sequence:

* Fast action phase.

    * Sybilla acts.
      She attacks a bandit, who reacts by dodging and therefore can't act later during the round.
      Note that the bandit can dodge even though his AGI is only 8.

    * The bandit leader acts.

    * The Players could act with Wolfgang, but choose to pass instead.

    * The GM must pass, as the remaining bandit can't act during this phase.
      The phase ends since both factions passed consecutively.

* Slow action phase.

    * Theobald acts.

    * The remaining bandit acts.

    * Wolfgang acts (since he didn't act during the previous phase due to early passing).

    * The GM and the Players must both pass, and the round ends.

{{% /details %}}
++++


== Chaos of combat

This is an optional rule you can use to represent the chaotic nature of combat and to reduce the amount of time spent to resolve fights if the Players suffer from analysis-paralysis and tend to overthink their turn.

* The Players aren't allowed to speak to each other unless their character spends a bonus action to say a short sentence.

* Each Player has 15 seconds to declare what they intend to do on their turn, otherwise they do nothing.
This doesn't include the time required to actually resolve the actions, take all the time you need to roll dice, assign damage, and so on.
