---
title: Health
weight: 30
prev: /rules/conditions
next: /rules/corruption
---
:toc:

== Health and damage

Characters have maximum health equal to their STR.
When they suffer damage, they reduce health by an equal amount, at most down to 0.

* Characters who lose at once half or more of their remaining health suffer *critical damage*.
Characters who suffer critical damage take the _incapacitated_ condition until the end of the stretch.
Sometimes, there might be additional penalties.

* Characters who lose all their remaining health suffer critical damage and additionally take the _dying_ condition.

* Characters who suffer at once damage matching or exceeding their STR are killed on the spot.

Lost health can be recovered by resting (see link:../rest[Rest]) or using healing items.

++++
{{% details title="Example" closed="true" %}}

Theobald has STR 9, therefore his maximum health is 9 as well.
When at full health, he suffers critical damage if he takes 5 or more damage at once.
If he takes damage and loses health, the amount necessary to trigger critical damage is reduced accordingly.
For example, once he is reduced to 4 health, he would suffer critical damage with just 2 points of damage.

No matter what his current health is, he dies immediately if he suffers 9 or more damage at once.

{{% /details %}}
++++


== Incapacitated and dying

_Incapacitated_ characters are unconscious or in terrible pain.
They are completely unable to act and defenceless.
They recover automatically at the end of the stretch.

_Dying_ characters die at the end of the next round.
If they recover at least 1 health before then, they are stabilized and out of danger, but must roll on the <<tb_injuries>> table and suffer the indicated penalty.

.Injuries
[[tb_injuries]]
[options='header, unbreakable', cols="^2,<14"]
|===
|D6 |Injury

|1 |*Scarred*.
The wound leaves a permanent mark, but there are otherwise no negative consequences.
Describe the scar as vividly as you can!

|2 |*Painful wound*.
Your STR is temporarily reduced by d4.

|3 |*Concussion*.
Your WIT is temporarily reduced by d4.

|4 |*Injured leg*.
Your AGI is temporarily reduced by d4.
You suffer from the _hobbled_ condition until you take a full rest (see link:../conditions[Conditions]).

|5 |*Injured arm*.
You suffer from the _arm injury_ condition until you take a full rest (see link:../conditions[Conditions]).
Roll a d2 to determine which arm is affected: 1) your secondary arm, 2) your primary arm.
If you get this injury a second time, the other arm is impacted.
If you get it a third time, nothing happens.

|6 |*Blinded eye*.
You suffer from the _eye injury_ condition until you take a full rest (see link:../conditions[Conditions]).
If you get this injury a second time, you suffer from the _blind_ condition until you take a full rest.
If you get it a third time, nothing happens.

|===


== Rolling for damage

Damage is usually rolled on a d4, d6, d8, d10, or d12.
If you roll the maximum possible number, you must re-roll the same die and add the new result to the previous roll minus 1.
Keep doing this as long as you keep rolling the maximum.

++++
{{% details title="Example" closed="true" %}}

Balthasar takes d6 damage and rolls a 6, the maximum: he must roll the d6 again and add 5 (6−1).
He rolls another 6: he must roll the d6 a third time and add 10 (5+5) to it.
Finally, he rolls 3, for a grand total of 13 damage: enough to kill most people!

{{% /details %}}
++++


== Impaired and enhanced damage

When characters suffer impaired damage, roll twice and keep the lower result.
Damage which is impaired multiple times is completely ineffective and ignored.

When characters suffer enhanced damage, roll twice and keep the higher result.
Multiple enhancements have no effect.

Factors enhancing and impairing damage at the same time cancel each other out.
For example, damage which is both impaired and enhanced is rolled normally, damage which is impaired once and enhanced twice is still enhanced, and damage which is impaired twice and enhanced once is impaired only once.

++++
{{% details title="Example" closed="true" %}}

Sybilla suffers d6 enhanced damage, therefore she must roll a d6 twice.
She rolls a 4 and a 6.
She must re-roll the second die and add 5: she rolls a 3 for a total of 5+3 = 8 damage.
The results of the two rolls are 4 and 8: since 8 is the greater roll, she suffers 8 damage.

Balthasar suffers d8 impaired damage, therefore he must roll a d8 twice.
He rolls 3 and 7, resulting in only 3 damage.

{{% /details %}}
++++


== Armour value

Armour value reduces incoming damage by a matching amount, even down to 0.
It is increased by wearing armour and holding shields.
'`Direct damage`' ignores armour value.

++++
{{% details title="Example" closed="true" %}}

Sybilla is wearing _light armour_, granting an armour value of 1.
She is hit by an axe-wielding bandit and suffers d6 damage.
She rolls a 2 and subtracts 1, resulting in only 1 point of actual damage.

{{% /details %}}
++++


== Ability changes

Abilities can change permanently or temporarily due to various effects.
If any ability is reduced to or below 0, even if only temporarily, the character dies.
Abilities can never exceed 19, or 15 for humans.

When STR is reduced, health must also be reduced by an equal amount, but not below 1.
Health loss due to STR loss doesn't cause critical damage.

Temporarily altered abilities are restored after a full rest (see link:../rest[Rest]).


== Death of the Player characters

Players whose character dies must immediately create a new one, who joins the company as soon as possible under whatever narrative pretext can be devised by the GM.
If all Player characters are _incapacitated_ at the same time, the GM decides what happens to the company (they might be killed, captured, rescued, robbed...).
If all Player characters die, the Players lose the game and must create a brand-new company.

Even though a dead Player character is promptly replaced, death still has consequences.
The replacement will be less experienced, and the other Player characters must pay for a funeral or permanently lose an omen, as described in the link:../omens/#_honour_the_dead[Honour the dead] section.
The GM may introduce additional or alternative penalties, as suitable to the scenario or the campaign.
For example, they might allow the Players a maximum number of deaths before the scenario or campaign is lost.

