---
title: Items
weight: 80
prev: /rules/rest
next: /rules/followers
---
:toc:

== Money

Money is measured in shillings (ʂ).
You should track it down to a quarter shilling.


== Encumbrance

Characters can carry up to 8 bulk unencumbered, and up to twice that _encumbered_.
_Encumbered_ characters move at half speed and must pass an additional STR save each time they make an AGI save.

* An item's bulk equals 1, unless otherwise indicated in its description.

* A character's bulk equals their carry limit: 8 for most characters.

* Groups of 16ʂ have bulk equal to ½.
15 or fewer shillings can be carried freely.


== Storage

Characters must have a reasonable way to store what they are carrying.
They can wear whatever makes sense and, if they wear some _clothes_, they are assumed to have enough containers (backpacks, pouches, pockets, scabbards, etc.) to store any amount of reasonably sized items.
Things with bulk higher than 2 (ladders, chests, other characters, etc.) can't be stored and require dedicated effort to carry, meaning they usually keep both hands occupied.


== Durability rolls

Each time an item is used in a way which might compromise its integrity, there is a 1:4 chance it is _damaged_.
Only roll if you are unsure if the item was _damaged_: if it's pretty clear it was _damaged_ or destroyed, it just happens.
_Damaged_ items can still be used, but are permanently destroyed on another failed durability roll.

++++
{{% details title="Example" closed="true" %}}

Balthasar uses a sword to try to break down a door.
After the attempt, the GM rules that this might have ruined the blade, and therefore asks for a durability roll.
Balthasar rolls a 1 on a d4, meaning that the sword was indeed _damaged_.

Sybilla violently throws a glass jar at the ground.
The glass just shatters, no durability roll required.


{{% /details %}}
++++


== Crafting

Everyone can craft crude, improvised items in a watch by using appropriate tools, consuming appropriate raw materials, and passing a STR or WIT save.
Such items always have a considerable flaw or disadvantage, as decided by the GM, typically the _fragile_ keyword.
Examples include: a club with sharp nails, a spear with a tip made of a beast's fang, a crude shelter to rest in the wilderness...

A few skills grant the ability to craft high-quality items of certain types.
Crafting an item takes a watch and requires a suitable workshop or tools, as indicated in the skill description.
No save is required unless trying to create a _master-crafted_ or _robust_ version of the item.
Consumable items can be crafted in batches of 2.

Raw materials cost ¼ the value of the item.
If the GM allows, they might sometimes be found in the area.
This might require some time to search.


== Item properties

* *Armour X*.
Increases armour value by X while worn. Characters can only wear one suit of armour. Equipping or unequipping armour takes a stretch. Armour is fitted to a specific character, and only those of similar size are able to wear it. When in doubt, there is a 1:8 chance it is possible.

* *Consumable*.
Discarded after use.

* *Health X/Y*.
This item has health equal to X and armour value equal to Y, and suffers damage like characters instead of using durability rolls. On critical damage, it is _damaged_ and can't be used until it recovers at least 1 health. Items can't heal like characters, but can be repaired. Sources of damage which can't realistically damage the items are completely ineffective (such as a sword against a metal door).

* *Fragile*.
Behaves as an already _damaged_ item: it is destroyed on a failed durability roll, weapons are destroyed on a roll of 1, shields and armour are destroyed upon taking 8 or more damage.

* *Robust*.
Only has a 1:8 chance of failing durability rolls.

* *Shield*.
Increases the armour value by 1 while held, but only against attacks you react against (counter, dodge, or guard) and attacks used to counter you. If you hold two shields at once, you still only increase armour value by 1, but against all attacks.

* *Vehicle X*.
Can carry X medium-sized characters and their gear. A character can be replaced by items for a total bulk of 16. The bulk of what's on the vehicle doesn't count towards the encumbrance of characters or operating it.

* *Weapon*.
Can be used to perform an attack while held, with the indicated damage and properties. Attacks made with one-handed weapons held in the non-dominant hand inflict impaired damage. Weapons of bulk 2 or more require both hands to attack and can't be used to attack characters you are grabbing. You don't have to track ammunition for ranged weapons.


== Attack properties

* *Blast*.
Targets all characters in a small zone and on its borders.

* *Direct damage*.
Inflicts full damage, ignoring the target's armour value.

* *Fire damage*.
Inflicts fire damage (it is direct damage).

* *Grab*.
Targets must pass a STR save to avoid being grabbed.

* *Holy damage*.
Only effective against _demons_ and _undead_.

* *Indirect range X*.
Can be used to attack up to range X. Can attack over obstacles, but can't attack within half range.

* *Poison*.
The target is exposed to poison of the specified type if they suffer at least 1 damage.

* *Range X*.
Can be used to attack up to range X.

* *Reload*.
This weapon can only be used only once per combat, since it takes a relative long time to reload it. In the few situations where it matters, a character can spend 10 rounds (1 minute) to reload the weapon.

* *Usage limit*.
Can only be used with the specified frequency.

* *Stun*.
Targets are _stunned_.


include::gen/ref_weapons.adoc[]

include::gen/ref_armour.adoc[]

include::gen/ref_combat_gear.adoc[]

include::gen/ref_artillery.adoc[]

include::gen/ref_vehicles.adoc[]

include::gen/ref_clothing.adoc[]

include::gen/ref_healing.adoc[]

include::gen/ref_poison.adoc[]

include::gen/ref_drugs.adoc[]

include::gen/ref_light_sources.adoc[]

include::gen/ref_academic_gear.adoc[]

include::gen/ref_exploration_gear.adoc[]

include::gen/ref_survival_gear.adoc[]

include::gen/ref_games.adoc[]

include::gen/ref_valuables.adoc[]

include::gen/ref_miscellanea.adoc[]


== Item modifiers

* *Fragile item* (÷4).
Gains the _fragile_ property.

* *Robust item* (×4).
Gains the _robust_ property.

* *Master-crafted weapon* (×4).
The damage die is improved: d4 to d6, d6 to d8, d8 to d10, d10 to d12.

* *Master-crafted armour or shield* (×4).
Bulk is halved.

* *Animal armour* (×1).
Made for dogs or other medium-sized animals without the _sturdy_ trait.

* *Sturdy animal armour* (×4).
Bulk is doubled. Made for horses or other medium-sized animals with the _sturdy_ trait.

* *Expensive item* (×4).
A particularly valuable version of another item. Good wine is an expensive _alcoholic drink_, a decorated sword is an expensive _martial hand weapon_, fancy outfits are expensive _clothes_, etc.

* *Luxury item* (×16).
An extremely valuable version of another item. Fine spirit is a luxury _alcoholic drink_, a gem-encrusted sword is a luxury _martial hand weapon_, aristocratic outfits are luxury _clothes_, etc.
