---
title: Items, Followers, & Services
weight: 60
prev: /rules/skills_traits_and_conditions
next: /rules/adventuring_rules
---
:toc:


== Item properties

* *Armour X*
Increases armour value by X while worn.
Characters can only wear one suit of armour.
Equipping or unequipping armour takes a stretch.
Armour is fitted to a specific character, and only those of similar size are able to wear it.
When in doubt, there is a 1:8 chance it is possible.

* *Consumable*.
Discarded after use.

* *Health X/Y*.
This item has health equal to X and armour value equal to Y, and suffers damage like characters instead of using durability rolls.
On critical damage, it is _damaged_ and can't be used until it recovers at least 1 health.
Items can't heal like characters, but can be repaired using a _toolbox_.
Sources of damage which can't realistically damage the items are completely ineffective (such as a sword against a metal door).

* *Fragile*.
Behaves as an already _damaged_ item: it is destroyed on a failed durability roll, weapons are destroyed on a roll of 1, shields and armour are destroyed upon taking 8 or more damage.

* *Robust*.
Only has a 1:8 chance of failing durability rolls.

* *Shield*.
Increases the armour value by 1 while held, but only against attacks you react against (counter, dodge, or guard) and attacks used to counter you.
If you hold two shields at once, you still only increase armour value by 1, but against all attacks.

* *Vehicle X*.
Can carry X medium-sized characters and their gear.
A character can be replaced by items for a total bulk of 16.
The bulk of what's on a vehicle doesn't count towards the encumbrance of the characters pulling it.

* *Weapon*.
Can be used to perform an attack while held, with the indicated damage and properties.
Attacks made with one-handed weapons held in the non-dominant hand inflict impaired damage.
Weapons of bulk 2 or more require both hands to attack and can't be used to attack characters you are grabbing.
You don't have to track ammunition for ranged weapons.


== Attack properties

* *Blast*.
Targets all characters in a small zone and on its borders.

* *Direct damage*.
Inflicts full damage, ignoring the target's armour value.

* *Fire damage*.
Inflicts fire damage (it is direct damage).

* *Grab*.
Targets must pass a STR save to avoid being grabbed.

* *Holy damage*.
Only effective against _demons_ and _undead_.

* *Poison*.
The target is exposed to poison of the specified type if they suffer at least 1 damage.

* *Range X*.
Can be used to attack up to range X.
If two numbers are shown (e.g. 2--4), the first one is the minimum range.

* *Reload*.
This weapon can only be used only once per combat, since it takes a relative long time to reload it. In the few situations where it matters, a character can spend 10 rounds (1 minute) to reload the weapon.

* *Usage limit*.
Can only be used with the specified frequency.

* *Stun*.
Targets are _stunned_.


== Item modifiers

* *Fragile item* (cost ÷4).
Gains the _fragile_ property.

* *Robust item* (cost ×4).
Gains the _robust_ property.

* *Master-crafted weapon* (cost ×4).
The damage die is improved: d4 to d6, d6 to d8, d8 to d10, d10 to d12.

* *Master-crafted armour or shield* (cost ×4).
Bulk is halved.

* *Animal armour* (cost ×1).
Made for dogs or other medium-sized animals without the _sturdy_ trait.

* *Sturdy animal armour* (cost ×4).
Bulk is doubled. Made for horses or other medium-sized animals with the _sturdy_ trait.

* *Expensive item* (cost ×4).
A particularly valuable version of another item. Good wine is an expensive _alcoholic drink_, a decorated sword is an expensive _martial hand weapon_, fancy outfits are expensive _clothes_, etc.

* *Luxury item* (cost ×16).
An extremely valuable version of another item. Fine spirit is a luxury _alcoholic drink_, a gem-encrusted sword is a luxury _martial hand weapon_, aristocratic outfits are luxury _clothes_, etc.


include::gen/ref_weapons.adoc[]

include::gen/ref_armour.adoc[]

include::gen/ref_combat_gear.adoc[]

include::gen/ref_healing.adoc[]

include::gen/ref_poison.adoc[]

include::gen/ref_drugs.adoc[]

include::gen/ref_light_sources.adoc[]

include::gen/ref_exploration_gear.adoc[]

include::gen/ref_survival_gear.adoc[]

include::gen/ref_academic_gear.adoc[]

include::gen/ref_games.adoc[]

include::gen/ref_valuables.adoc[]

include::gen/ref_miscellanea.adoc[]

include::gen/ref_artillery.adoc[]

include::gen/ref_vehicles.adoc[]



== Followers

* *Animal* (*).
Check the link:../bestiary[Bestiary] section for profiles and values in shillings.
For each type of training it has received, double the cost.

* *Labourer* (16ʂ).
Hired for a day to carry stuff and perform menial labour.
Won't fight or provide other services.

* *Expert* (32ʂ).
Hired for a day to provide some form of expertise (guide, knowledge, healing, etc.)
Won't fight, carry stuff, or perform menial labour.

* *Mercenary* (64ʂ).
Hired for a day to fight.
Won't carry stuff, perform menial labour, or provide services other than fighting.


== Services

* *Bank deposit* (*).
Deposit money in a bank by paying ¼ of the deposited sum.
You can withdraw deposited money for free.

* *Item storage* (*).
Safely store items by paying ¼ of their value.
You can take them back for free.

* *Loan* (*).
Borrow a sum of money, but you must pay back twice as much.
Debts left behind by dead Player characters are transferred onto the other Player characters.
If debts aren't repaid in a timely fashion, new loans might be refused and the character might be harassed by debt collectors.

* *Healing* (16ʂ).
Recover health equal to half STR.

* *Surgeon* (64ʂ).
Perform a surgery.

* *Doctor* (64ʂ).
Diagnose a poison or disease.

* *Lodging, daily rest* (4ʂ).
Provides a place to sleep, food, and water during a daily rest.

* *Lodging, full rest* (64ʂ).
Provides a place to sleep, food, and water during a full rest.

* *Repair* (*).
Repair a damaged item by paying ¼ of its value.
Items with the _health_ property recover 2 health per watch spent repairing them.

* *Workshop* (4ʂ).
Price to rent a workshop for a day, for example, to make use of the _alchemy_ or _craft_ skill.

* *Courier* (*).
Delivers a message to a recipient.
The cost is 1ʂ per region of distance.
The cost might be higher through dangerous areas.

* *Funeral* (512ʂ).
A funeral for a dead Player character.
Costs half if the body was recovered.

* *Transportation* (*).
Transportation via stagecoach, boat, or ship, to a specific destination for a person.
It costs is 2ʂ per region of distance.
This includes a place to sleep, but food must be purchased on top of that (4ʂ per person per day).
The cost might be higher through dangerous areas.
