---
title: Movement
weight: 100
prev: /rules/advancement
next: /rules/hazards
---
:toc:

== Maps

The scenario should provide maps illustrating the regions and sites where the adventure takes place.
During play, the GM can copy the maps on paper as the Players explore locations, gradually revealing their layout and features.


== Areas

Maps are divided into areas, which can vary in size and shape to accommodate the features of the location.
There are three types of areas: zones, sectors, and regions.

* *Zones* are used in maps representing buildings, dungeons, and other small sites.
A zone covers an area of about 4 m by 4 m, such as a small room, a portion of a large room, a corridor, etc.

* *Sectors* are used in maps representing towns, districts, and other large sites.
A sector covers an area of about 400 m by 400 m, such as a city district, a large building, a garden, etc.

* *Regions* are used in maps representing vast regions.
A region covers an area of about 10 km by 10 km, such as a whole city, a portion of a forest, a mountain pass, etc.


== Positioning

Characters can be located in an area or on the border between two areas.
There is no relevant limit on how many characters can fit inside a sector or a region.

Up to 8 characters can fit inside a zone, and up to 2 characters can fit on the border between two zones.
These numbers are halved for particularly tiny and cramped zones, and doubled for particularly large and open zones.
Borders representing a door or similar small passages can typically hold only a single character.
Characters can't move through or into a zone or zone border which is already full.


== Range

Ranged attacks, powers, and other effects have a range expressed in number of zones.
To determine if two zones are within range, find the shortest path between them and count how many zones it crosses, excluding the originating one.

Characters on a border are considered to be in either zone for the purpose of range.
This means that characters in a zone are at range 0 from all characters in the same zone and on all its borders, and characters on a border are at range 0 from other characters on the same border or in either of the two zones it divides.

Characters at range 0 from each other are said to be '`nearby`' and can be targeted by melee attacks and other short range effects.


== Movement speed

Characters can move by two areas per time unit: two zones in a round, two sectors in a stretch, or two regions in a watch.
Moving to or from the border between two areas counts as moving by half an area.

Movement speed can be reduced down to half zone per time unit, and if further halved movement isn't possible at all.
These factors halve movement speed:

* The _encumbered_ and _hobbled_ conditions.

* Moving between sectors and regions in harsh weather (heavy rain, snow, scorching heat, etc.).

* Moving between sectors and regions without following an open path or road (through forests, swamps, mountains, hills, labyrinthic alleys, etc.).


== Special movement

* *Sprint*.
Move at double speed (usually 4 zones in a round) across open terrain.
If the terrain presents obstacles (a furnished room, thick vegetation...) passing an AGI save is required to avoid tripping and suffering d4 direct damage.
You can't sprint for more than a stretch consecutively.

* *Sneak*.
Move silently and behind cover.
You remain undetected if you pass an AGI save.
Trivial in loud and dark places, impossible on very noisy surfaces and in plain view.

* *Balance*.
When moving on difficult ground (slippery, uneven, narrow...), you must pass an AGI save or trip.
When you trip, you suffer d4 direct damage and can't move further until the next round.
Impossible on very difficult ground (for example slippery _and_ narrow).

* *Leap*.
Pass an AGI save to leap across a significant obstacle or gap.
Trivial for tiny gaps, impossible for very large gaps.

* *Climb*.
When you end a round hanging from a surface, or you reach the top of the climb, you must pass an AGI save or fall.
Trivial on easy surfaces (such as ladders), impossible on smooth surfaces (such as walls).
Attacks made while climbing are impaired, and at least one hand must be used to keep hold of the surface.

* *Swim*.
When you enter turbulent waters or start a round in turbulent waters, you must pass an AGI save or become _incapacitated_.
When you are _incapacitated_ in water, you might suffocate (link:../hazards/#_suffocating[Suffocating]).
Attacks made while in water are impaired.

Only one of the special movement options described above is possible at a time.
For example, you can't sprint while climbing, or sneak while swimming.
Characters who are proficient in one form of movement can combine it with another one, but this makes the task challenging.


== Optional rule: grids

You can use a square grid instead of zones to keep track of where the characters are.
A square represents a distance of 1.5 metres (ca. 5 ft feet).
Each square can be occupied by a single medium-sized character.

To convert ranges in zones to ranges in squares, multiply by 4.
For example, a range of 2 zones would correspond to a range of 8 squares.

Anything affecting a whole zone, such as blast attacks, affects a 3 squares by 3 squares area instead.

