---
title: Perception
weight: 110
prev: /rules/movement
next: /rules/hazards
---
:toc:

== Perception and knowledge

The GM has the task of revealing to the Players what they can see, hear, smell, feel, and know.
They can take the Player characters' skills, background, and history to evaluate what they might know or notice.
For example, a character with the _medicine_ skills would be able to recognize the symptoms of a disease and know how it will develop, while a character with the _rat-catcher_ background would surely know a lot about those pesky rodents.

The Players should ask clarifying questions if the situation isn't clear to them, and point out if they think their character has a skill or property which might help to know more about something.
This helps the GM run the game in the best possible way!


== Concealed elements

Concealed elements (traps, hidden caches, secret passages, hiding characters...) can automatically be detected by spending some time to search the area.
If they aren't perfectly concealed they can also be detected passively, without a search, when nearby by passing a group WIT save.

Searching a zone or a sector takes a stretch or a watch respectively and reveals all concealed elements in it.
Searching a region takes 2 watches and only reveals a single concealed element within it.
Two characters can split and search a region in a single watch.


== Detecting other characters

When two groups encounter each other, they must each make a group WIT save.
If at least one member passes, they notice the other group.

Groups which are being reckless (making noise, talking loudly, carrying a light in the dark...) are automatically detected and can't detect the other group unless they are being reckless as well.
Groups which are well hidden and silent (for example laying in ambush in a thick forest) can't be detected by a WIT save, only by a search, and automatically detect even cautious groups.

If only one group notices the other, it has the opportunity to decide how to approach the encounter: leaving, sneaking, launching an ambush, attempting to parley, etc.
If both or neither group notices the other, the two sides stumble upon each other and the encounter can't be avoided.


== Sneaking

Characters who haven't been detected can attempt to move around while staying hidden by sneaking, following the rules described in the link:../movement[Movement] chapter.
It must still be realistically possible to sneak: there must be cover or darkness to hide, and the possibility to move without significant noise.
