---
title: Player Characters
weight: 30
prev: /rules/core_rules
next: /rules/careers
---
:toc:

== Creating a Player character

Player characters are created randomly, but feel free to discuss with the GM if you wish to change some details.
You can follow the process below step by step or use the online link:../../character_generator[Character Generator].

. *Abilities*.
Roll on the <<tb_starting_ability_scores>> to determine an array of three scores and assign them randomly to the three abilities.

.. Roll a d3 to assign the highest score: 1) STR; 2) AGI; 3) WIT.

.. Roll a d2 to assign the middle score to one of the remaining abilities, skipping over the one which was already assigned.

.. Finally, assign the lowest score to the last remaining ability.

. *Career*.
Determine your past career by rolling on the <<tb_careers>> table.
Check its description in the link:../careers[Careers] chapter.
Re-roll if you get the same career as another Player.

. *Skills*. You start with two skills granted by your career.
Check their description in the link:../skills_traits_and_conditions[Skills, Traits, & Conditions] chapter.

. *Assets*.
You start with 4ʂ, plus the items, money, and followers granted by your career, plus the items and money you get by rolling on the <<tb_starting_items>> table.
If you start with sacred or profane _power scrolls_, roll on the <<tb_sacred_powers>> or <<tb_profane_powers>> tables respectively to determine what power it holds.
Re-roll if you get the same result as another Player on any table.

. *Secondary properties*.
You start with health equal to your STR (plus 3 if you have the _tough_ skill), 0 corruption, 0 mana, and 2 omens.
Your armour value depends on your starting items.

. *Name and description*.
Name and portray your character using words, drawings, or a combination of the two, as you prefer.
You can roll on the <<tb_masculine_first_names>>, <<tb_feminine_first_names>>, <<tb_last_names>>, <<tb_appearance>>, <<tb_personality>>, and <<tb_reasons_to_adventure>> tables if you need inspiration.

After all Player characters have been created, describe how they know each other.
Go around the table and define a relationship for each pair of Players sitting next to each other, excluding the last pair.
You can roll on the <<tb_relationships>> table for inspiration.

++++
{{% details title="Example" closed="true" %}}

David is creating a new character.

1. He rolls 7 on a d12 for the abilities scores: 11, 7, and 6.
He rolls a d3 to assign the highest score (11) and gets a 2 (AGI).
Furthermore, he rolls a d2 to assign the middle score (7) and gets a 2 again (WIT in this case, skipping over AGI).
His character's starting abilities are therefore: **STR** 6, **AGI** 11, **WIT** 7.

2. He rolls a 1 on a d4 and an 11 on a d12 for the career: _soldier_.

3. His career grants him the _skilled blow_ and _skilled shot_ skills.

4. He starts with the following assets:

    * His career provides _clothes_ and a _martial great weapon_.

    * He rolls 2 on a d3 and 9 on a d12 for his starting item: one dose of _flash powder_.

    * He has a total of 8ʂ (base of 4ʂ, plus 4ʂ for the career, and no extra money from the starting item roll).

5. He notes down his secondary properties: health is 6 (equal to STR), corruption is 0, omens are 2, mana is 0, and armour value is 0.

6. He finally describes and names his character.

{{% /details %}}
++++


== Character advancement

During a campaign, the GM may grant the Player characters an advancement when they achieve significant progress, for example at the end of a scenario or when certain milestones or objectives are reached.

* At odd advancements (1st, 3rd, 5th, 7th, 9th, etc.), characters permanently increase their abilities by a total of 2 points.
Remember that no ability can exceed 15 for humans, or 19 in general.

* At even advancements (2nd, 4th, 6th, 8th, 10th, etc.), characters gain a new skill of their choice.
They must be able to reasonably explain how they have learnt it (a mentor, past experiences, etc.).

* Characters with the _sorcery_ skill can increase their mana by 1 instead of taking the standard advancement.
Mana can't exceed 6.


== Character creation tables

.Starting ability scores
[[tb_starting_ability_scores]]
[options='header, unbreakable', cols="^1,^4,^1,^4,^1,^4"]
|===
|D12 |Scores
|D12 |Scores
|D12 |Scores
|1 |8, 8, 8
|2 |9, 8, 7
|3 |9, 9, 6
|4 |10, 7, 7
|5 |10, 8, 6
|6 |10, 9, 5
|7 |11, 7, 6
|8 |11, 8, 5
|9 |12, 6, 6
|10 |12, 7, 5
|11 |13, 6, 5
|12 |14, 5, 5
|===

include::gen/tb_careers.adoc[]

include::gen/tb_starting_items.adoc[]

include::gen/tb_sacred_powers.adoc[]

include::gen/tb_profane_powers.adoc[]


== Description tables

include::gen/tb_appearance.adoc[]

include::gen/tb_personality.adoc[]

include::gen/tb_reasons_to_adventure.adoc[]

include::gen/tb_masculine_first_names.adoc[]

include::gen/tb_feminine_first_names.adoc[]

include::gen/tb_last_names.adoc[]

include::gen/tb_relationships.adoc[]
