---
title: Rest
weight: 60
prev: /rules/omens
next: /rules/items
---
:toc:

== Day rest

Characters can spend a watch to take a day rest.
After two watches spent doing something else, they must do so or temporarily reduce all abilities by 1.
On the fourth watch they are too exhausted to do anything else and are forced to take a day rest.

Characters taking a day rest must eat, drink, and sleep.
If they satisfy all needs, they recover health and mana to the maximum.
If they don't, they recover no health and no mana and temporarily reduce an ability by 1 for each unsatisfied need: STR if they didn't eat, AGI if they didn't drink, and WIT if they didn't sleep.

In a settlement it is possible to pay 4ʂ for lodging, which includes food, drinks, and a bed.
In the wilderness it is necessary to consume a _ration_ to eat, consume a unit of _water_ to drink (unless there is plenty of drinkable water in the area), and have a _camping kit_ to sleep.
Animals don't need a _camping kit_, and they don't need a _ration_ or a _drink_ while in their natural habitat, as they can forage for themselves.


== Foraging

Characters might find themselves in the tricky situation where they run out of food or water in the wilderness.
In this case, foraging is necessary to find the resources to rest and survive.

Foraging for food in the wilderness takes a watch.
Characters who do so roll on the <<tb_foraging>> table to see if they find something edible.
_Rations_ gathered in this way are perishable and are discarded if not consumed before the next day rest.

In many environments, water is plenty, and you don't need to track the need for it.
If the characters find themselves in an area where water is scarce, they need to spend a watch and pass a WIT save to find a source of drinkable water.
In places completely devoid of water, such as a desert, finding water is impossible.

.Foraging
[[tb_foraging]]
[options='header, unbreakable', cols="^2,<14"]
|===
|D8 |Foraging result

|1 |*Fruits and vegetables*.
You find a _ration_ unless you are in a desolate environment.

|2 |*Dubious fruits and vegetables*.
You find a _ration_ unless you are in a desolate environment, but you aren't sure if it's edible.
If consumed there is a 1:4 chance that it makes you sick: you temporarily reduce all abilities by 1.

|3-4 |*Fish*.
You find a _ration_ if you have a _fishing kit_ and there is a nearby body of water in your region.

|5-6 |*Small game*.
You find a _ration_ if you have a _trapping kit_, and you aren't in a desolate environment.

|7 |*Big game*.
Unless you are in a desolate environment, you find 4 _rations_ if you pass a WIT save to track a prey and then roll 4 or more damage with a ranged attack to kill it.

|8 |*Nothing*.
You come back empty-handed.

|===



== Full rest

Characters can spend a week in a settlement to take a full rest.
It costs 64ʂ to pay for lodging, healing, and entertainment.
They recover health and mana to the maximum, restore omens to the maximum, remove all conditions, and restore temporarily modified abilities to their original score.
A full rest is the best way to get rid of long-lasting penalties due to injuries (ability reductions and negative conditions).


== Rest activities

While taking a full rest, a character can perform a single rest activity.
Possible rest activities are:

* Any action taking a watch to resolve (trading in a settlement, crafting an item, gathering rumours...).

* Training animals (see the link:../followers[Followers] chapter).

Activities taking less than a watch can be performed freely during a full rest, within reason.
