---
title: Tips for the GM
weight: 180
prev: /rules/mounts_and_vehicles
next: /rules/bestiary
---
:toc:

== Mapping the world

One of your tasks as the GM is to map the locations where the game takes place.
You don't need extremely detailed maps: just draw some connected areas, write a few words to describe them, and add a few elements with which the Players can interact.

* *Overland map*.
You usually need a region-based map, providing the top-level setting for the scenario or campaign.
This is often a town plus the surrounding wilderness: forests, swamps, mountains, etc.
For smaller one-shot scenarios, however, you might not need this.
Very large campaigns might contain multiple linked overland maps.

** You should pick a general landscape for each region (grassland, forest, swamp, mountains...) and draw roads and rivers.

** Each region can contain one or more interesting sites, usually towns or adventure locations.
You can decide which sites are easy to find, and which ones are concealed and require a search to be located.

** You should have an idea of what type of creatures and denizens populate each region.
This will help you decide whom the characters encounter.

* *Site maps*.
You should represent each site with a zone-based map.
Large sites might be made of multiple connected sectors, each one with its own zone-based sub-map.

** You should provide a very brief description of each area to present it to the Players when they first enter it.

** You can populate each area with interesting elements and hazards that the Players can examine and interact with: treasure chests, furniture, puzzles, traps, obstacles...
You don't have to describe everything down to the tiniest details: focus on what would make the game interesting.
There is no need to list every piece of furniture in the room!

* *Encounter maps*.
Sometimes, encounters happen outside of a site, for example while travelling in the overland map.
It can be useful to have a few maps ready to use when this happens.


== Managing the game flow

A large part of the game will see the Players travelling across regions and exploring sites.
They will often encounter GM characters and interact with them in some way, mostly through dialogue or combat.

*Scale*.
You should use different maps and keep track of time using different units depending on what's happening.

* When travelling, use the overland map and keep track of time using watches.

* When exploring a site, use the site map and keep track of time using stretches.

* During an encounter, use the site map or a suitable encounter map.
You can assume the encounter lasts a whole stretch.
If a fight breaks out, use the combat rules to track time and actions.

*Travel and exploration procedure*.
When travelling in the overland map or exploring a site, you can use the following procedure to run the game:

. The Players take turns performing an action, in any order.
They can take turn together if they wish to cooperate on something.

** Anything taking a watch or stretch, depending on the time scale in use, is a valid action.

** Quicker actions can be performed freely, within reason.
Perform one action at a time: if a quick action is performed, that character can take another action before the watch or stretch ends, until it performs a longer action or the GM rules they have done enough.

. As the GM, you do the same for your characters, when relevant.
You don't need to decide what all characters in the whole world do every time, just focus on what is relevant in the current situation!

. Once all characters have taken a turn, the watch or stretch ends and a new one begins.

*Encounter procedure*.

. Determine which group is aware of the other one as described in the link:../encounters#_detecting_other_characters[Detecting other characters] section.

. Based on the result of the previous point, you, the Players, or both declare how they intend to approach the situation: attacking, attempting to parley, sneaking around...

. The encounter transitions to a parley, to combat, or back to site exploration, depending on the choice.


== Typical actions

*Typical overland travel actions*.
Anything taking a watch.

* *Move* across regions.
The company should typically move together: splitting the company at this scale is very hard to manage.

* *Search* the region for hidden sites and locations (takes 2 watches).

* *Forage* to look for food or water.

* *Take a day rest* in the wilderness or in a nearby settlement.

* *Trade* in a nearby settlement.

* *Craft* items.

* *Explore a site*.
For simplicity, typically this consumes the whole watch, no matter how long the Player spend there.
This includes the time spent to travel to the site and the time spent there.

*Typical site exploration actions*.
Anything taking a stretch.

* *Move* across sectors.

* *Search* a zone.

* *Slow interactions* with the environment (picking a lock, reading a scroll...).

*Typical site exploration quick actions*.
Anything taking a round or less.

* *Move* across zones.

* *Examine* something.

* *Quick interactions* with the environment (opening a door, reading a short message...).


== When to ask for a save or contest

* A save should only be required for challenging, risky actions.
Trivial actions should succeed automatically.
Impossible actions should fail automatically.

* Prefer a save over a contest whenever possible, especially in asymmetric situations where a side is clearly more at risk.
Use contests only for competitions and other symmetric situations.

* Roll for a contest only if it's uncertain who would win.
Characters who are clearly superior win automatically without rolling.

++++
{{% details title="Example" closed="true" %}}

Climbing a ladder is trivial: it can be done without rolling for a save.
Climbing a vertical rocky surface, or a slippery ladder, is challenging: a save is required.
Climbing a sheer, smooth surface is impossible: characters just can't do it.

Two characters engaging in arm wrestling should determine the winner with a STR contest: it is a symmetric competition.
A character who is pushed by someone else should make a STR save to stand their ground: it is an asymmetric challenge, and the pusher is not at risk.

Two people racing against each other would make an AGI contest to see who wins.
A person racing against a horse in an open filed would always lose, no roll required.

{{% /details %}}
++++


== Picking an ability for a save or contest

* Use STR for physical challenges mainly decided by might or fortitude, where someone large, powerful, and tough would have the advantage.

* Use AGI for physical challenges mainly decided by finesse or initiative, where someone athletic, nimble, and quick would have the advantage.

* Use WIT for mental challenges.

++++
{{% details title="Example" closed="true" %}}

The most fitting ability to open a stuck door would be STR, since it requires brute strength.

The most fitting ability for climbing is AGI, since it requires dexterity and athleticism.
STR might sounds like the most fitting option, but a large, heavy, muscular person would have a harder time climbing than a fit and nimble person!

The most fitting ability to persuade someone would be WIT, since it is a mental challenge.
However, if the "persuasion" attempt is made via threat of violence, STR might also be an option!

{{% /details %}}
++++



== Consequences of failing a save

Failing a save should always have negative consequences, but doesn't necessarily mean a failure in the action itself.
In particular, a failed save should never halt progress through the scenario, so in such a situation the GM might want to let the action succeed but at a cost.

* The character suffers harm (damage, corruption, a negative condition...).

* Time is lost, resources are exhausted, equipment is damaged...

* The character angers someone, attracts unwanted attention, is put on a spot...

++++
{{% details title="Example" closed="true" %}}

The most intuitive penalty for failing a save while climbing would be falling and taking damage.
However, depending on the situation, the GM might just rule that it takes longer to make the climb, or that an item falls from the character's backpack and breaks.

{{% /details %}}
++++


== Give Players a choice

When a Player wants to attempt a risky action, you should declare if a save or contest is required, on what ability, and risking what penalties.
The Player should then be given the option to change their mind and do something different.
Due to the flexibility of the rules, it might not always be clear to a Player if an action would require a save in your mind, so it's good to give an opportunity to change their approach!

This also applies to hazards and dangers: make sure that the Players have some clue about their existence.
Blindly walking into a death trap with no chance to avoid it might be realistic, but it's not fun!

You can also try to pose the Player in front of a dilemma: let them choose if they want to attempt a risky solution requiring a save, or to give up something in order to succeed automatically.
This creates interesting decisions, which are what make the game fun!

++++
{{% details title="Example" closed="true" %}}

Balthasar and Sybilla are exploring an ancient cave.
The GM describes what they see: a deep chasm is blocking their way.

Balthasar declares he wants to jump across.
The GM says that the chasm is rather large, and an AGI save would be required to make it safely to the other side.
On a failure, Balthasar would fall down into the darkness.
The GM asks Balthasar if he wants to go on and take the risk: Balthasar might have imagined a smaller gap and might not have expected that a save would be required, so it's important to give a choice after this is clear.

Balthasar decides that it's not worth taking the risk, and decides to keep walking along the chasm instead to see where it leads.

{{% /details %}}
++++


== Be generous with information

The Players see the world through your descriptions.
They can't read your mind, and sometimes they might miss or forget some details.
In order for the game to be enjoyable for them and take informed decision, it is essential that they have a good and complete picture of the situation.

To this end, be generous with the information you give them.
Err on the side of saying too much rather than too little.
Also, remind the Players to ask for more information and clarifications if something isn't clear.



== Tips for creating characters

As the GM, you will have to create a lot of characters to use during the game.

* To quickly create an unimportant human character on the spot, just pick a suitable career: that's all you need!
Assume that abilities have average score (all 8).

* Creating important human characters is a bit more involved, but not too much.
Just decide their abilities scores, their skills, their traits, and their equipment.
You can also give 1 or 2 omens to essential characters.

* To create monsters, demons, and other creatures, just let your imagination run wild!
It can be useful to take an existing profile as a starting point, and build on top of that.


== Tips for creating careers and skills

You can expand the roster of careers and the list of skills as you see fit.
Don't worry too much about "`balance`": the game isn't supposed to be, and in any case the Players work together.
Instead, make sure that new skills are actually useful: nobody would like to waste a skill slot for something that never comes up!

Feel free to ban careers and skills which aren't useful in your campaign.
If you are planning to set the campaign in an arid desert, the _boatman_ career and the corresponding skills will likely be rather useless!


== Tips for creating items

* *Weapons*.
Damage should preferably not exceed d10, otherwise the _skilled blow_ and _skilled shot_ skill wouldn't work with it.

* *Armour*.
Total armour value should preferably not exceed 3: higher values would make a character almost invulnerable.
Since shields provide 1 point of armour value, suits of armour should never exceed 2.

* *Cost*.
You can use existing items as a reference on how to price new ones.
You might have noticed that item prices are mostly powers of 4.
This makes it easy to halve prices without rounding, and items on a certain price category are worth as much as 4 items of the lower category, which is a nice conversion scale.


== Tips for creating powers

* *Range and duration*.
Profane powers typically have _personal_ or _near_ range and _instant_ or _stretch_ duration.
They can be enhanced, so it makes sense to keep these properties on the lower side.
On the other hand, sacred powers can't be altered and take longer to invoke, so feel free to improve their range and duration as it makes sense.

* *Enhancements*.
Rather than creating multiple similar profane powers, think if you could define a generic one which can be enhanced for different effects.
