---
title: Combat
weight: 140
prev: /rules/encounters
next: /rules/powers
---
:toc:

== Combat procedure

During combat, time is tracked using rounds.
The factions involved in the fight alternate taking turns with a character or passing.
Each character can only take turn once per round.
When all factions pass consecutively, the round ends.
At the end of the round, you must make morale checks if necessary (see <<_morale>>).


== Initiative

The faction holding the initiative can decide which faction acts first each round.
Initiative is held by the faction which started the fight, or is assigned randomly if that's unclear.


== Taking a turn

During their turn characters can do the following, in any order:

* Perform a _bonus action_.

* Perform a _main action_ or another _bonus action_.

* _Move_ by a zone.
It is possible to split movement before, after, and between actions.

Alternatively, characters can take their turn outside of the normal round order to perform a _reaction_ in response to a specific trigger.
A reaction takes the whole turn and doesn't allow for a movement or a bonus action.


== Main actions

* *Full movement*: move 2 zones, and optionally perform a special movement (see link:../movement/#_special_movement[Special movement]).

* *Attack* an enemy (see <<_attacking>>).

* *Invoke* a profane power (see link:../powers/#_invoking_profane_powers[Invoking profane powers]).

* Attempt to *distract*, *intimidate*, or *taunt* an enemy (see link:../encounters/#_manipulation[Manipulation]).


== Bonus actions

* *Pick up* or *put down* something.

* *Equip* or *unequip* an item.
Swapping two items is two bonus actions.
Armour can't be changed during a fight.

* *Use a consumable item*, such as a _healing draught_, an _antidote_, or a dose of poison.

* *Interact* with the environment (open a door, pull a lever...).
The GM may rule it takes a main action to perform complex interactions.

* *Say a few words*.


== Reactions

* *Counter* an attack (see <<_reacting_to_an_attack>>).

* *Dodge* an attack (see <<_reacting_to_an_attack>>).

* *Guard* a nearby ally (see <<_reacting_to_an_attack>>).

* *Hide behind* a nearby ally or a grabbed enemy (see <<_reacting_to_an_attack>>).

* Perform an *opportunity attack* (see <<_opportunity_attacks>>).


== Attacking

Attacking an enemy is a main action.
In normal situations, attacks hit and inflict damage to the target automatically.
However, attacks made in challenging circumstances require passing a WIT save to hit.

Unarmed attacks inflict d4 impaired damage.
Armed attacks inflict damage depending on the weapon used.
The attacker may choose to voluntarily hold back an attack to inflict impaired damage.
If the target is nearby and _incapacitated_, the attacker may choose to deliver a final blow and kill them.

*Melee attacks*.
Target a nearby character.
Hitting a target who is not visible requires passing a WIT save or the attack misses and inflicts no damage.

*Ranged attacks*.
Target a visible character within the indicated range.
Hitting targets beyond half range or while moving requires passing a WIT save or the attack misses and inflicts no damage.
Targeting a character beyond half range while moving, or a character who is not visible, isn't possible.

*Indirect ranged attacks*.
Can be directed at targets which aren't directly visible and over obstacles, but can only target beyond half range.
A WIT save to hit is always required.
Attacking while moving isn't possible.


== Reacting to an attack

Targets of an attack may attempt to dodge, counter, or hide behind a nearby character as a reaction.
The choice must be made before rolling for damage but after the WIT save to hit, if required.
Targets who are unaware of their attacker can't react.

*Dodge*.
Make an AGI save: on a pass the attack misses.

*Counter*.
Perform a suitable attack against the attacker.
Both characters roll for damage at the same time.
Whoever suffers the most damage, after reductions, is hit first.
In case of a tie both characters are hit at the same time.
Attacks with multiple targets can only be countered by a single target.

*Hide behind a nearby character*.
Choose a nearby character, who must agree with the action.
This character becomes the new target of the attack.
They can perform their own reaction.

*Guard*.
A character who is nearby the target of an attack can react by guarding them.
They become the new target of the attack.
Since they have spent their reaction to guard, they can't normally counter or dodge.


== Opportunity attacks

Characters can make an opportunity attack as a reaction against nearby enemies moving away.
The target's movement is interrupted and the attack is resolved, after which their turn resumes if they are still alive and  conscious.

It isn't normally possible to react to an opportunity attack, since the target is already spending the turn to act, but some skills might give an opportunity to do so.


== Protection from attacks

*Concealment* partially obscures vision to the target.
Damage is impaired.

*Cover* offers physical protection.
The target's armour value is increased by 1 unless the attack is powerful enough to penetrate the cover.

*Barriers* completely block attacks.
If a character peaks behind cover to attack, they can be still countered and the barrier only counts as cover.


== Blast attacks

Blast attacks hit a zone and target all characters in it and on its borders.

Melee blast attacks hit the attacker's zone and don't target the attacker themselves.
They can't miss.

Ranged blast attacks hit any zone within range and target the attacker as well if directed at their own zone.
If they miss, they are deviated and hit a random neighbouring zone.
You can assign a number to each neighbouring zone and roll a die to determine which one.


== Attack stunts

The attacker can propose an alternative effect to the target instead of inflicting damage (cutting a limb, forcing a surrender, etc.).
This must be done before the target decides whether to react but after the WIT save to hit, and the alternative effect must make sense and be approved by the GM.
The target can either accept the proposed effect or resolve the attack as normal.
It isn't possible to react if the effect is accepted.


== Non-lethal attacks

Non-lethal attacks don't inflict damage but instead force the target to pass a save or suffer negative consequences.
They can be dodged and countered and can be used to counter.
Since they inflict no damage they are always resolved last in case of a counter.

*Disarm*.
A nearby target must pass a STR save or drop a weapon chosen by the attacker.

*Grapple*.
A nearby target must pass a STR save or be grabbed by the attacker.
Grabbed characters are _entangled_ for as long as their enemy keeps hold of them.

* Characters who are grabbing another character can move together with them and attack them while keeping hold, but doing anything else automatically frees the grabbed character.

* They can also shove the grabbed character, freeing them but forcing them to move by half a zone and/or pushing them into a hazard in their zone.

* Finally, they can hide behind the grabbed character as a reaction to an attack.
The grabbed character has no option but become the new target of the attack.


== Sneaking in combat

Characters who launch an ambush are concealed at the start of the fight.
Hiding later during the fight requires being out of sight for a while or a major distraction.
The GM should keep the position of concealed characters hidden from the Players, and should control their characters so that they realistically ignore concealed Player characters.

Enemies attacked by a concealed character are taken by surprise and can't react.
At the start of the fight, concealed characters play a bonus turn during which only they can act.

Concealed characters are revealed when they make noise or become visible to the enemy.
Actions which might reveal a character include: attacking, invoking a power, talking, moving without sneaking, walking right in front of the enemy, etc.


== Morale

Groups must make a morale check after being reduced to half or less their original number during a fight.
Characters fighting alone must do so after taking damage reducing their health to half or less the maximum.
Morale checks are made at the end of the round, during the morale phase.

Make a group WIT save: those who fail must surrender or retreat, but those who pass aren't subject to morale for the remainder of the stretch.
Characters who are immune to fear are also immune to morale.


== Surrendering

Characters can spend their turn to surrender, throwing their weapons away, putting their hands up, etc.
Their turn is wasted, but they might be spared by the enemy.
Surrendering characters who are harmed by the enemy can resume fighting normally even if they previously failed a morale check.


== Chases

Short chases can be played out using the combat rules.
Chases over long distances can be resolved with the fleeing character making a group AGI save: those who pass escape, those who fail are reached by the pursuers.
If the fleeing characters can move faster or keep the speed for longer, the save is not required.
If the opposite is true, escaping is impossible.


== Combat gear degradation

After a fight, make a durability roll for all weapons and armour which were used at least once.
This represents damage to the equipment and depleting ammunition.

_Damaged_ weapons and shields are destroyed if they are used to attack and a 1 is rolled on the damage die.
_Damaged_ shields and armour are destroyed by attacks inflicting at least 8 damage before armour reduction (shields are destroyed first).

Many mundane items can be used as improvised weapons.
They work as a _simple hand weapon_ or a _simple great weapon_, but are handled as if they were already _damaged_.


== Optional rule: fast and slow activations

You can use this optional rule if you would like WIT to influence the order in which characters act during the round and you don't mind a little bit of extra complexity.

At the beginning of each round the GM openly rolls a d20.
The result is the "`fast action threshold`" or FAT.
You can leave the d20 on the table as a reminder of this value.

The round is divided in two phases: fast action and slow action.

* During the fast action phase, only characters whose WIT matches or exceeds the FAT can take their turn.

* During the slow action phase, all characters who haven't acted yet (either by choice or because their WIT is lower than the FAT) can take their turn.

Each phase ends when all factions pass consecutively, as per the usual rules.
Characters can react during any phase, no matter what their WIT score is.

++++
{{% details title="Example" closed="true" %}}

Balthasar (WIT 12), Sybilla (WIT 6), and Theobald (WIT 9) are fighting against two bandits (WIT 8) and their leader (WIT 10).
The Players have the initiative.

The GM rolls a d20 to determine the fast action threshold: the result is 9.
During the fast actions phase, only Balthasar, Theobald, and the bandit leader can act.
Sybilla and the two bandits can't, because their WIT is lower than 9.

The fast actions phase begins.
Since the Players have the initiative, they take turn first.
Theobald goes first, followed by the bandit leader.
Balthasar could act too, but the Players choose to pass instead.
During his turn, Theobald attacks a bandit, who chooses to dodge: they can do so even though they couldn't normally act during this phase.

The slow actions phase begins.
All characters who haven't acted yet can take a turn now: Balthasar, Sybilla, and one of the bandits, the one who didn't dodge.
The Players again start because they have the initiative.
Sybilla goes first, followed by the bandit, and ending with Balthasar.

{{% /details %}}
++++


== Optional rule: the chaos of combat

This is an optional rule you can use to represent the chaotic nature of combat and to reduce the amount of time spent to resolve fights if the Players suffer from analysis-paralysis and tend to overthink their turn.

* The Players aren't allowed to speak to each other unless their character spends a bonus action to say a short sentence.

* Each Player has 15 seconds to declare what they intend to do on their turn, otherwise they do nothing.
This doesn't include the time required to actually resolve the actions, take all the time you need to roll dice, assign damage, and so on.
