---
title: Items
weight: 80
prev: /rules/rest
next: /rules/followers
---
:toc:

== Money

Money is measured in shillings (ʂ).
You should track it down to a quarter shilling.


== Encumbrance

Characters can carry up to 8 bulk unencumbered, and up to twice that _encumbered_.
_Encumbered_ characters move at half speed and must pass an additional STR save each time they make an AGI save or fail.

* An item's bulk equals 1, unless otherwise indicated in its description.

* A character's bulk equals their carry limit: 8 for most characters.

* Groups of 64ʂ have bulk equal to ½.
63 or fewer shillings can be carried freely.


== Storage

Characters must have a reasonable way to store what they are carrying.
They can wear whatever makes sense and, if they wear some _clothes_, they are assumed to have enough containers (backpacks, pouches, pockets, scabbards, etc.) to store any amount of reasonably sized items.
Things with bulk higher than 2 (ladders, chests, other characters, etc.) can't be stored and require dedicated effort to carry, meaning they usually keep both hands occupied.


== Durability rolls

Each time an item is used in a way which might compromise its integrity, there is a 1:4 chance it is _damaged_.
Only roll if you are unsure if the item was _damaged_: if it's pretty clear it was _damaged_ or destroyed, it just happens.
_Damaged_ items can still be used but are permanently destroyed on another failed durability roll.

++++
{{% details title="Example" closed="true" %}}

Balthasar uses a sword to try to break down a door.
After the attempt, the GM rules that this might have ruined the blade, and therefore asks for a durability roll.
Balthasar rolls a 1 on a d4, meaning that the sword was indeed _damaged_.

Sybilla violently throws a glass jar at the ground.
The glass just shatters, no durability roll required.


{{% /details %}}
++++



include::gen/ref_item_keywords.adoc[]

include::gen/ref_weapon_keywords.adoc[]

include::gen/ref_weapons.adoc[]

include::gen/ref_armour.adoc[]

include::gen/ref_gear.adoc[]

include::gen/ref_artillery.adoc[]

include::gen/ref_vehicles.adoc[]

include::gen/ref_item_modifiers.adoc[]
