---
title: Omens
weight: 50
prev: /rules/corruption_and_mutation
next: /rules/rest_and_recovery
---
:toc:

== Maximum omens

Omens represent luck and divine favour.
Player characters start with 2 omens, the maximum they can accumulate.
Omens can be spent to gain various advantages, and are regenerated by taking a full rest (see link:../rest_and_recovery[Rest & Recovery]).

GM characters normally don't have any omens, but exceptions can be made for particularly important individuals.


== Spending omens

* Reroll a failed save.
You can even do so when you fail a group save, in which case you reroll the die only for yourself, other characters are unaffected.

* Reroll a contest against the character just above you in the ranking, swapping positions if you win.
If multiple characters have omens to spend, resolve from the bottom of the ranking.

* Reroll when you suffer damage, keeping the lowest roll.
You can't reroll damage you inflict.

* Reroll when you must determine if you suffer soulblight after taking corruption, keeping the result you prefer.

* Reroll on a table, picking the result you prefer.

* Save yourself from certain death.
This can be used both against instant death effects (for example if you suffer at once damage matching your STR) or when you die due to the _dying_ condition.
Your health is set to 1, you suffer critical damage, and you lose the _dying_ condition if you have it.
Finally you must roll on the link:../health_and_damage/#tb_injuries[Injuries] table, however in this case the effects of the injury (ability reduction and conditions) are permanent!


== Honour the dead

When a Player character dies, the other members of the company must pay for a funeral at the latest until their next full rest.
It costs 512ʂ, halved if the dead character's body is returned.

Failing to pay for a funeral brings bad luck: all other Player characters permanently reduce their maximum omens by 1.
If they already have 0 omens, they suffer no additional penalties.
