---
title: Omens
weight: 50
prev: /rules/corruption
next: /rules/rest
---
:toc:

== Maximum omens

Omens represent luck and divine favour.
Player characters start with 2 omens, the maximum they can accumulate.
Omens can be spent to gain various advantages, and are regenerated by taking a full rest (see link:../rest[Rest]).

GM characters normally don't have any omens, but exceptions can be made for particularly important individuals.


== Spending omens

Characters can spend omens in the following ways.
It is possible to spend multiple omens on the same roll.

* Reroll a failed save or lost contest.
If it's a contest, repeat the contest against the character just above in the ranking, swapping positions on a win.
If it's a group save, other characters are unaffected by the new roll.
In a contest, characters towards the bottom of the ranking decide whether to spend an omen first.

* Reroll the amount of damage suffered, keeping the lowest roll, or reroll when checking for soulblight after suffering corruption, keeping the roll you prefer.
It isn't possible to reroll damage inflicted against others.

* Save yourself from death.
Your health is set to 1, you suffer critical damage, and you lose the _dying_ condition, if you have it.
Finally you must roll on the link:../health/#tb_injuries[Injuries] table, however in this case the effects of the injury (ability reduction and conditions) are permanent!

++++
{{% details title="Example" closed="true" %}}

Theobald (STR 9) is hit by a poisonous dart and must pass a STR save to resist the toxin.
He rolls a 10, a failure, but decides to spend an omen to reroll.
This time he gets a 1: he succeeds!

Balthasar (AGI 10), Sybilla (AGI 10), and Theobald (AGI 6) are racing against each other, and must resolve it as an AGI contest.
After their rolls, the ranking is: Sybilla, then Balthasar, then Theobald.
Theobald decides to spend an omen to repeat the contest against Balthasar.
Theobald wins, so the ranking is now Sybilla, then Theobald, then Balthasar.
Balthasar could spend an omen as well to retry, but chooses not to.
Theobald now decides to spend another omen to try to surpass Sybilla as well.
This time he fails, so the ranking doesn't change.
Since he has no omens left, the contest is over.

Sybilla suffers d4 damage.
She rolls 4 (the maximum), then 2, for a total of 5 damage.
She decides to spend an omen to reroll the damage.
This time she rolls a 2, so she only suffers 2 damage.

Balthasar suffers 4 corruption, bringing the total to 4, and rolls a d12 to check for soulblight.
He gets a 4, which would mean 4 direct damage.
He spends an omen to reroll and this time gets a 5.
Since it's a better result, he keeps it and suffers no damage.

Sybilla (STR 8, current health 6) suffers 10 damage, which would be enough to kill her on the spot.
She spends an omen to save herself: her health is set to 1 and she is _incapacitated_.
She rolls a 6 on the Injuries table, meaning she permanently loses an eye.

{{% /details %}}
++++


== Honour the dead

When a Player character dies, the other members of the company must pay for a funeral at the latest until their next full rest.
It costs 512ʂ, halved if the dead character's body is returned.

Failing to pay for a funeral brings bad luck: all other Player characters permanently reduce their maximum omens by 1.
If they already have 0 omens, they suffer no additional penalties.
