---
title: Perception
weight: 110
prev: /rules/movement
next: /rules/hazards
---
:toc:

== Perception

The GM reveals to the Players what they can see, hear, smell, and feel.
The GM should lean on the side of providing too much information rather than too little: the Players can't play effectively if they don't have enough information.
The Players should ask questions to clarify any doubts if they don't have a clear picture of the situation in their mind.


== Concealed elements

Concealed elements (traps, hidden caches, secret passages, hiding characters...) can automatically be detected by spending some time to search the area.
If they aren't perfectly concealed they can also be detected passively, without a search, when nearby by passing a group WIT save.

Searching a zone or a sector takes a stretch or a watch respectively and reveals all concealed elements in it.
Searching a region takes 2 watches and only reveals a single concealed element within it.
Two characters can split and search a region in a single watch.


== Detecting other characters

When two groups encounter each other they must each make a group WIT save.
If at least one member passes, they notice the other group.

Groups which are being reckless (making noise, talking loudly, carrying a light in the dark...) are automatically detected and can't detect the other group unless they are being reckless as well.
Groups which are well hidden and silent (for example laying in ambush in a thick forest) can't be detected by a WIT save, only by a search, and automatically detect even cautious groups.

If only one group notices the other, it has the opportunity to decide how to approach the encounter: leaving, sneaking, launching an ambush, attempting to parley, etc.
If both or neither group notices the other, the two sides stumble upon each other and the encounter can't be avoided.


== Knowledge

The GM provides information to the Players based on what their characters should realistically know.
They can take their skills, background, and history into account.
For example, a character with the _medicine_ skills would be able to recognize the symptoms of a disease and know how it will develop, while a character with the _rat catcher_ background would surely know a lot about those pesky rodents.

The Players should remind the GM if they think their characters might know more about a specific topic, and the GM can reveal additional information if deemed appropriate.


== Languages

Player characters can speak Common, the lingua franca of the Kingdom.
The ability to speak additional languages is granted by skills or the character's history.

Characters can't read, write, or perform anything but very simple calculations unless they have a skill which grants this ability: education is a privilege for the few!
