---
title: Perception & Knowledge
weight: 110
prev: /rules/positioning_and_movement
next: /rules/hazards
---
:toc:

== Perception

The GM reveals to the Players what they can see, hear, smell, and feel.
The GM should lean on the side of providing too much information rather than too little: the Players can't play effectively if they don't have enough information.
The Players should ask questions to clarify any doubts if they don't have a clear picture of the situation in their mind.


== Concealed elements

Concealed elements (traps, hidden caches, secret passages, hiding characters, etc.) can automatically be detected by spending some time to search the area.
If they aren't perfectly concealed they can also be detected passively, without a search, when nearby by passing a group WIT save.

Searching a zone or a sector takes a stretch or a watch respectively and reveals all concealed elements in it.
Searching a region takes 2 watches and only reveals a single concealed element within it.
Two characters can split and search a region in a single watch.


== Detecting others

When two groups encounter each other they must each make a group WIT save.
If at least one member passes, they notice the other group.

Groups which are being reckless (making noise, talking loudly, carrying a light in the dark, etc.) are automatically detected and can't detect the other group unless they are being reckless as well.
Groups which are well hidden and silent (for example laying in ambush in a thick forest) can't be detected by a WIT save, only by a search, and automatically detect even cautious groups.

If only one group notices the other, it has the opportunity to decide how to approach the encounter: leaving, sneaking, launching an ambush, attempting to parley, etc.
If both or neither group notices the other, the two sides stumble upon each other and the encounter can't be avoided.


== Sneaking

Characters who haven't been noticed may attempt to move without being detected, for example to approach an enemy or to move away unnoticed.

They must be able to move silently and unseen, for example in the shadows or behind some form of cover, and must pass an AGI save to avoid detection.
Sneaking in trivial situations, such as in very noisy or dark areas, requires no save, while sneaking on very loud surfaces or in the open is simply impossible.

Movement speed is halved while sneaking.


== Knowledge

The GM provides information to the Players based on what their characters should realistically know.
The Players can ask the GM if their characters know more about a specific topic based on their skills and background, and the GM can reveal additional information if deemed appropriate.


== Languages

Player characters can speak Common, the main language spoken in the Kingdom.
The ability to speak additional languages is granted by skills.

Characters can't read, write, or perform anything but very simple calculations unless they have a skill which grants this ability: education is a privilege for few people!
