== Poison

* *Scorpion oil* (16ʂ, bulk ½).
_Consumable_.
Bloodstream paralysing poison (_incapacitated_ until the end of the stretch).


* *Candlestick root* (16ʂ, bulk ½).
_Consumable_.
Ingested paralysing poison (_incapacitated_ until the end of the stretch).


* *Butterfly sting* (16ʂ, bulk ½).
_Consumable_.
Bloodstream soporific poison (_incapacitated_ until the end of the watch or until damaged).


* *Dream sand* (16ʂ, bulk ½).
_Consumable_.
Ingested soporific poison (_incapacitated_ until the end of the watch or until damaged).


* *Powdered heavenstone* (16ʂ, bulk ½).
_Consumable_.
Bloodstream corrupting poison (4 corruption at the end of the stretch).


* *Beastman blood* (16ʂ, bulk ½).
_Consumable_.
Ingested corrupting poison (4 corruption at the end of the stretch).


* *Black adder venom* (16ʂ, bulk ½).
_Consumable_.
Bloodstream damaging poison (d12 direct damage at the end of the stretch).


* *Reaper's spice* (16ʂ, bulk ½).
_Consumable_.
Ingested damaging poison (d12 direct damage at the end of the stretch).


* *Chimera spit* (64ʂ, bulk ½).
_Consumable_.
Bloodstream lethal poison (death at the end of the stretch).


* *Dark lotus* (64ʂ, bulk ½).
_Consumable_.
Ingested lethal poison (death at the end of the stretch).


* *Disease vial* (64ʂ, bulk ½).
Contains a liquid infected with some disease. Can be thrown at range 2 or be used to coat weapons or taint items.


