== Trait list

* *Addicted*.
The character is addicted to a specific substance. On a day rest, they must consume it or temporarily reduce WIT by 1. On a full rest, they must consume 4 units of it or temporarily reduce WIT by 1 for each missing unit.


* *Corrupting*.
Anyone touched by this character suffers the indicated amount of corruption. This includes targets of melee attacks, unless they successfully dodge.


* *Fast*.
The character moves at double speed.


* *Frail*.
The character halves carry limit and bulk.


* *Frightening*.
The character causes fear within range 4. They are immune to _frightening_ characters and treats _terrifying_ characters as _frightening_.


* *Hovering flyer*.
The character can fly, and can attack and stay still while flying.


* *Landing flyer*.
The character can fly, but can't attack and can't stay still while flying.


* *Mutation*.
The character has the mutations listed after the trait. See the Corruption chapter for more information.


* *Permanent condition*.
The character permanently applies the effects of the listed conditions.


* *Power*.
The character can invoke the listed power once per watch, with the listed amount of EP. The power always works and doesn't inflict corruption.


* *Regeneration*.
The character recovers half the amount of lost health each round, at the start of their turn. Fire damage stops regeneration for a watch.


* *Slow*.
The character moves at half speed.


* *Split*.
When they suffers critical damage, the character splits into two copies of themselves, each with health equal to the remaining amount and STR to match.


* *Sturdy*.
The character doubles carry limit and bulk.


* *Swooping flyer*.
The character can fly, and can attack while flying, but can't stay still while flying.


* *Terrifying*.
The character causes terror within range 4. They are immune to _frightening_ and _terrifying_ characters.


