== Acrobat

You used to earn your fare by performing spectacular and dangerous acrobatic feats. +
*Skills*: _acrobatics_, _climb_. +
*Items*: clothes (comfortable and colourful leotard), rope (made of silk), wooden pole.

== Agitator

You know how to incite the people with fervent speeches. You were partly responsible for the bloody riots of 1461: you swear you did it for your ideals, not money. +
*Skills*: _fleet footed_, _leadership_. +
*Items*: alchemist's fire, clothes (working class attire), scroll (pamphlet denouncing the Emperor, or at least they told you so: you can't read after all).

== Apothecary

You are a master at mixing miraculous ointments and potent poisons. +
*Skills*: _craft medicine_, _craft poison_. +
*Items*: apothecary tools, clothes (spotless white apron and bags to carry ingredients), dream sand, medicinal herbs.

== Artisan

You know how to keep equipment in good order: nothing is more dangerous than a blunt sword or a cracked shield. +
*Skills*: _crafting_, _piercing strike_. +
*Items*: clothes (thick leather apron), toolbox.

== Assassin

For the right amount of coins, you can get rid of anyone. +
*Skills*: _sneak attack_, _stealth_. +
*Items*: black adder venom, clothes (dark cloak), missile hand weapon (hand crossbow).

== Barber-surgeon

A sharp razor and a steady hand are required for both a clean shave and delicate surgeries. +
*Skills*: _heal_, _strike to injure_. +
*Items*: clothes (bloodstained apron), surgical tools.

== Beggar

You spent your days sitting in the corner of busy roads, hoping for a few shillings from generous passers-by. +
*Skills*: _disease resistance_, _frugal_. +
*Items*: alcoholic drink, clothes (dirty, stinky rags), crutch.

== Berserker

You are a savage, bloodthirsty warrior, barely able to control your bloodlust. +
*Skills*: _battle frenzy_, _cleave_. +
*Items*: clothes (blood-splattered furs decorated with the skulls of your foes), martial great weapon (glaive).

== Boatman

You have ferried passengers and smuggled goods along the many rivers flowing across the Kingdom. +
*Skills*: _river lore_, _swim_. +
*Items*: clothes (wet and mouldy), fishing tools.

== Bodyguard

You worked for the rich and powerful, protecting them from robbers and other scum. +
*Skills*: _protect_, _shield mastery_. +
*Items*: clothes (enhancing your muscles), medicine box, shield.

== Bone picker

One person's rubbish is another person's treasure: you scour the roads, graves, and gutters looking for something valuable to sell for a few pennies. +
*Skills*: _frugal_, _quick draw_. +
*Items*: clothes (mismatched clothes scavenged from various dumpsites), crutch, junk (bag of dung), simple hand weapon (femur, _fragile_).

== Bounty hunter

You used to roam the cities and the countryside, capturing wanted criminals to collect the bounties on their head. +
*Skills*: _disarm_, _strike to stun_. +
*Items*: clothes (large coat and wide-brimmed hat), manacles & key, net.

== Brawler

Your fists are your weapon and your arms can bend iron: nobody is stronger than you! +
*Skills*: _brawling_, _wrestling_. +
*Items*: alcoholic drink, chain, clothes (hand wraps to protect your knuckles).

== Burglar

There is no lock you can't open and no safe you can't crack. +
*Skills*: _burglary_, _pack rat_. +
*Items*: clothes (comfortable and with generous pockets), lock picks, metal file.

== Charlatan

You are a cunning liar, able to convince people of almost anything. +
*Skills*: _blather_, _charm_. +
*Items*: clothes (fake city watch uniform, won't stand scrutiny), scroll (filled with scribbled nonsense), silver jewel (fake necklace).

== Coach driver

You worked for a coaching company, driving stagecoaches through the dangerous roads of the Kingdom and protecting them with your trusty blunderbuss. +
*Skills*: _drive carts_, _steady aim_. +
*Items*: clothes (coat and wide brimmed hat, for the rain), long gun (blunderbuss).

== Cutpurse

Some are born with too much: those wealthy nobles aren't going to notice if they are a few shillings short. +
*Skills*: _steal_, _stealth_. +
*Items*: clothes (hood covering your face), gold jewel (gold necklace with a noble family emblem, stolen).

== Duellist

You are a skilled duellist, constantly looking for a worthy opponent to hone your skills. +
*Skills*: _ambidextrous_, _fast strike_. +
*Items*: clothes (a few stitched up cuts), martial hand weapon (thrusting sword), simple hand weapon (parrying dagger).

== Fire eater

You were a performer at a travelling carnival, executing a vast array of exciting tricks with fire. +
*Skills*: _contortionist_, _fire eating_. +
*Items*: alcoholic drink, clothes (bare chested, lest your shirt catches fire), missile hand weapon (throwing knives, you like to juggle with them), torch.

== Footpad

You have spent years mugging unaware victims in shady alleys and dark forest roads, and occasionally killing for money. +
*Skills*: _sneak attack_, _strike to stun_. +
*Items*: clothes (scarf to cover your face), garrotte, simple hand weapon (cudgel, ideal to knock people out).

== Gambler

Luck come and goes at the gaming table, but it has never abandoned you, not with the help of a few clever tricks. +
*Skills*: _lucky_, _play games_. +
*Items*: cards (marked), clothes (large pockets), dice (loaded).

== Hunter

When you hunt in the dark forests of the Kingdom, you sometimes wonder if you really are the hunter or rather the prey. +
*Skills*: _bushcraft_, _hunt_. +
*Items*: clothes (decorated with trophies from your preys), missile great weapon (crossbow).

== Jester

You have spent your life making a fool of yourself to entertain the nobles, but you will have the last laugh! +
*Skills*: _acrobatics_, _blather_. +
*Items*: clothes (colourful, with a bell hat), simple hand weapon (stick with bells, jingles cheerfully when it strikes), smoke bomb.

== Knight

With your honour lost, and no coin left to your name, you wander on your steed, selling your sword for money. +
*Skills*: _ride_, _skilled blow_. +
*Items*: clothes (colourful livery). +
*Followers*: light horse (Bartadan, trained for combat, old and lame: permanent _hobbled_ condition).

== Labourer

Your bones and muscles have been hardened by years of toiling under sun and rain. +
*Skills*: _pack rat_, _tough_. +
*Items*: clothes (drenched in sweat), ration (packed lunch), simple great weapon (shovel).

== Lawyer

Nobody is above the law, but you can help those with enough money wiggle through its many loopholes. +
*Skills*: _gossip_, _political lore_. +
*Items*: book (Laws of the Kingdom), clothes (court attire), ration (cooked capon, payment received from a customer).

== Messenger

Time is of the essence when carrying messages across the Kingdom, and you sure are a fast runner. +
*Skills*: _fleet footed_, _ride_. +
*Items*: clothes (dusty and sweaty), scroll (sealed letter, no addressee), scroll case.

== Miner

Crawling through dark, cramped tunnels, breaking rocks and breathing dust, wasn't the life you deserve. +
*Skills*: _dark vision_, _piercing strike_. +
*Items*: cage (containing a canary), clothes (sweaty and dusty), simple great weapon (pickaxe).

== Noble

Your house has fallen, and you must now mingle with the lowly scum, but the day will come when you can reclaim what's yours by birthright! +
*Skills*: _leadership_, _poison resistance_. +
*Items*: clothes (ostentatious fripperies, old and full of holes), mirror, signet ring (proof of your identity).

== Outlaw

The hills and woods are teeming with people escaping the law, such as yourself. +
*Skills*: _bushcraft_, _skilled shot_. +
*Items*: clothes (greenish cloak), missile great weapon (bow).

== Peasant

Your life was simple: growing crops and tending to livestock, trying to put enough food on the table to survive another winter. +
*Skills*: _animal handling_, _tough_. +
*Items*: clothes (stinking of manure). +
*Followers*: chicken (Bertha, dumb and brave), pig (Hans, picky about food).

== Pedlar

You made a small fortune transporting and trading exotic goods, but you lost everything because of a bad business decision. +
*Skills*: _bargain_, _languages_. +
*Items*: clothes (excessive amounts of cheap fake jewellery), clothes (expensive, made of silk), darkroot, perfume.

== Physician

You are an erudite doctor, knowledgeable about poison, disease, surgery, and healing. +
*Skills*: _heal_, _medicine_. +
*Items*: clothes (spotless black coat), cure-all, medicine box.

== Pit fighter

You have fought for money in illegal arenas and as a judicial champion for hire. +
*Skills*: _dodge blows_, _fast strike_. +
*Items*: clothes (torn, dusty, and covered in old blood), martial hand weapon (Spear), missile hand weapon (javelins).

== Priest

Yours is the burden to teach and guide people so that they don't succumb to the lure of darkness. +
*Skills*: _faith_, _incorruptible_. +
*Items*: book (Holy Scriptures), clothes (priestly robes and religious paraphernalia), power scroll (sacred).

== Raconteur

You have travelled far and wide across the kingdom, singing songs and acting out enthralling stories. +
*Skills*: _acting_, _music_. +
*Items*: clothes (flamboyant and fashionable), music instrument (fiddle).

== Rat catcher

Rats are everywhere and nobody likes them. You make a living getting rid of them, but you swear they are getting bigger and nastier by the day... +
*Skills*: _disease resistance_, _poison resistance_. +
*Items*: clothes (partly made of rat fur), trapping tools. +
*Followers*: small dog (Brutus, trained to hunt rats, small but vicious).

== Scholar

Hunched over dusty ancient tomes, you have accumulated vast amounts of knowledge: time to put it into practice! +
*Skills*: _alchemy_, _erudition_. +
*Items*: book (blank, you can't wait to fill it with your learnings), clothes (night gown and comfortable shoes), looking glass, quill & ink.

== Sharpshooter

Your skill with a bow or a gun has no equals: you can shoot a moving squirrel from half a mile away. +
*Skills*: _steady aim_, _skilled shot_. +
*Items*: clothes (wide brimmed hat to shade your eyes), long gun (arquebus).

== Slayer

There is good pay for slaying giant monsters: it's a dangerous job, but you are brave and foolish enough to do it. +
*Skills*: _dodge blows_, _monster slaying_. +
*Items*: clothes (thick hardened leather, cut, burnet, scratched, and torn), martial great weapon (huge battleaxe).

== Soldier

You have fought for the Kingdom and seen the horrors of war, the nightmares will never stop. +
*Skills*: _cleave_, _skilled blow_. +
*Items*: clothes (uniform from your regiment, has seen better days), martial great weapon (halberd).

== Soothsayer

You are cursed with the ability to see what others can't, and have witnessed the end of the world. +
*Skills*: _divination_, _lucky_. +
*Items*: clothes (hooded robes), divination tools.

== Thug

A sturdy club is the best way to send a strong message, as you like to say. +
*Skills*: _brawling_, _intimidate_. +
*Items*: alcoholic drink, clothes (covering your face), crimson weed.

== Tomb robber

Precious treasures are buried in ancient crypts and old tombs: their previous owners aren't going to miss them. +
*Skills*: _burglary_, _climb_. +
*Items*: clothes (capacious rucksack to store the loot), crowbar, rope.

== Townsman

Townsfolk such as yourself are the backbone of the Kingdom: shop owners, traders, local officials... +
*Skills*: _bargain_, _gossip_. +
*Items*: candle, clothes (fashionable but practical), pipe & tobacco.

== Witch hunter

Warlocks, witches, and sorcerers are a threat to mankind: they are destined to meet their end in the flames of a pyre. +
*Skills*: _magic sense_, _magic shield_. +
*Items*: alchemist's fire, 2× blessed water, clothes (wide brimmed hat, pitch black clothes).

== Wizard

You are a secretive scholar of the esoteric arts: many fear you, and with good reason. +
*Skills*: _meditation_, _sorcery_. +
*Items*: clothes (comfortable robes), 2× power scroll (profane).

== Zealot

You have a dark past and many sins to atone for: you are going to save your soul by purging the heretic! +
*Skills*: _battle frenzy_, _bravery_. +
*Items*: book (Holy Scriptures), clothes (bloodstained monastic habit), crimson weed.

