== Miscellanea

* *Animal trophy* (16ʂ, bulk 2).
Skin, feathers, bones, or other body parts of a medium animal. Divide the cost by 4 and the bulk by 2 for each side below medium. Multiply the cost by 4 and the bulk by 2 for each size above medium.


* *Cage* (256ʂ, bulk 8).
Can hold a medium character. Divide the cost and bulk by 4 for each side below medium. Multiply the cost and bulk by 4 for each size above medium.


* *Clothes* (16ʂ).
All you need to cover yourself! Include belts, pouches, bags, and other containers to hold items of bulk 2 or less.


* *Crutch* (4ʂ).
_Hobbled_ characters can use it to walk.


* *Disguise kit* (16ʂ, bulk 2).
All you need to disguise your appearance! Includes makeup, wigs, fake beards, hats, eyepatches, clothing, etc.


* *Divination tools* (16ʂ, bulk 2).
Include a crystal ball, tarot cards, divination bones, etc. Used in combination with the _divination_ skill.


* *Junk* (1ʂ).
Skull, bag of dirt or dung, dirty pillow, chalk, etc.


* *Lockbox & key* (4ʂ).
Can hold items for a total bulk of 1.


* *Looking glass* (16ʂ).
See distant details.


* *Lucky charm* (16ʂ, bulk ½).
_Consumable_.
You can use it instead of spending an omen. It then loses its power and turns into _junk_.


* *Manacles & key* (4ʂ).
Bind someone's hands.


* *Mirror* (16ʂ).
A simple hand mirror.


* *Music instrument* (16ʂ).
Drums, fiddle, flute, lyre, lute, etc.


* *Perfume* (16ʂ, bulk ½).
_Consumable_.
An exquisite scent.


* *Prosthesis* (16ʂ).
Replaces a lost limb. Works as a _crutch_ if it replaces a lost leg.


* *Saddle* (16ʂ, bulk 2).
Required to ride a mount. Includes saddlebags.


* *Sealing wax* (4ʂ, bulk ½).
_Consumable_.
Used to seal and sign letters in combination with a _signet ring_.


* *Signet ring* (16ʂ, bulk ½).
Proof of identity, used to stamp _sealing wax_.


* *Toolbox* (16ʂ, bulk 2).
Includes hammer, saws, nails, etc. Spend a watch and pass a STR or WIT save to repair a damaged item, but on a fail the item is destroyed. If the item has the _health_ property, repair or inflict 2 damage instead on a pass or fail.


* *Wheelbarrow* (64ʂ, bulk 8).
Can carry a total bulk of 8, without counting towards encumbrance.


* *Wooden pole* (4ʂ, bulk 2).
2 metre long.


