== Profane powers

* *Animal shape*.
_Touch_, _stretch_.
Target a creature, who turns into a animal of your choice but of the same size category. You must carry an _animal trophy_ of the chosen animal (the skin, feathers, scales, shell, etc.), which envelop and merge with the target during the transformation and return to their previous state when the spell ends. Targets keep their intelligence, but can't speak. The spell doesn't influence the target's equipment, which simply falls to the ground.

** 2 EP -- Turn into an animal which differs by one size category. You can apply this enhancement multiple times to increase the size difference.

* *Arcane lock*.
_Touch_, _stretch_.
Target an item which can be opened and closed, such as a door, a box, or a bottle. The target is locked and can only be opened by a trigger of your choice (a password, a gesture, contact with a specific item, etc.). However, it is still possible to break it.

** 1 EP -- The target emits a loud noise if someone attempts to open or damage it without using the proper trigger.

* *Bewitch*.
_Touch_, _stretch_.
Target a creature. The target becomes infatuated with you: they will behave in a friendly and open way and will be willing to help. However, the spell breaks if the target is hurt or clearly taken advantage of.

** 1 EP -- Target another creature, who replaces you as the one towards whom attitude is improved.

* *Burning vengeance*.
_Touch_, _stretch_.
Target a creature of human intelligence. Name a person they know and remind them of how they have been wronged by them, no matter if by a small or a big matter. The target becomes obsessed with an irrational desire to take revenge by killing the named person, and they will fully devote themselves to this end.


* *Eldritch blast*.
_Touch_, _instant_.
Target a character or an item. The target is hit by a force blast which works as an attack inflicting d10 damage. If range is enhanced to _sight_, the power behaves as a ranged attack and follows normal attack rules.

** 1 EP -- The power inflicts fire, lightning, cold, or heat damage.
** 1 EP -- The attack gains the _blast_ property.

* *False death*.
_Touch_, _stretch_.
Target a creature. The target falls like a stringless puppet and appears dead, even upon close examination. However, they are still very much alive: they can perceive their surroundings and must breathe, eat, and drink to survive.


* *Fiery taste*.
_Touch_, _stretch_.
Target up to 4 _rations_ and/or _alcoholic drinks_. _Rations_ become extremely spicy: those who consume must pass a STR save or succumb to a terrible stomachache and be _incapacitated_ until the end of the stretch. _Alcoholic drinks_ become extremely potent: drinking one counts as drinking two. Characters with the _fire eating_ skill aren't affected.


* *Flawed resurrection*.
_Touch_, _instant_.
Target the lifeless heart of a creature who died no longer than a stretch ago. A new body forms around the heart and the target's spirit is called back to inhabit it, effectively resurrecting them. The regeneration process takes a watch. The new body is different from the original both in appearance and capabilities. Reassign STR, AGI, and WIT randomly, as done during character creation. Skills and personality don't change, but traits associated with the physical body are removed. Once the resurrection is complete, the target immediately suffers 4 corruption.

** 2 EP -- Target a creature who died no longer than a watch ago.
** 4 EP -- Target a creature who died no longer than a day ago.

* *Gift of speech*.
_Touch_, _stretch_.
Target a creature, who gains the ability to speak one language you can understand.


* *Hold secret*.
_Touch_, _stretch_.
Target a creature of human intelligence and name a topic. The target is physically unable to talk about the topic, and will compulsively lie if forced to.


* *Illusion*.
_Touch_, _stretch_.
Target a small zone. You can create an illusion within its boundaries, which can affect sight, hearing, and smell, but not touch. While you are within range, you can concentrate on the illusion to change it or animate it. While you aren't concentrating, the illusion remains frozen in the state you left it, and only disappears when the power ends.


* *Joyous appearance*.
_Touch_, _stretch_.
Target a creature. The target's appearance becomes perfect and free of any blemish. Signs of disease, affliction, old age, and mutation completely disappear. The appearance might in fact be too perfect, almost uncanny (the skin is too smooth, the cheeks are too rosy, etc.). The change in appearance is real, not an illusion, but any underlying illness or problem isn't cured and still has effect.


* *Levitation*.
_Touch_, _stretch_.
Target a creature. The target temporarily gains the _flyer (lander)_ trait.

** 1 EP -- Improve to _flyer (swooper)_.
** 2 EP -- Improve to _flyer (hoverer)_.

* *Miasma of chaos*.
_Touch_, _stretch_.
Target a small zone. The zone is filled with red mist flowing from the ground. Characters entering or starting their turn in the affected area suffer 1 corruption. The mist blocks visibility.

** 1 EP -- Double the amount of corruption.
** 1 EP -- The mist covers all zones within range 1 of the targeted one. Enhance multiple times to double the range.

* *Occult consultation*.
_Touch_, _stretch_.
Target the remains of a creature whose spirit is still lingering in the area (typically, if they died no longer than a watch ago). You may ask one question, but they aren't forced to answer truthfully, if at all. If you enhance range to _connection_, you may contact the spirit of a long dead creature, even without their remains. In this case, they will answer by knocking on the door to the underworld. This means they can only answer with a number, or a yes-or-no question.


* *Plague vessel*.
_Touch_, _stretch_.
Target a _sick_ creature. You absorb the disease from the target, who is instantly healed. You carry the disease in your body without suffering its effect. You can attempt to discharge it by touching another creature before the power ends. The target can resist the infection with a STR save as usual. If they resist, the disease stays in your body, and you can attempt to discharge it again later. If the power ends before you discharge the disease, you are infected by it yourself, without chance of a save.

** 1 EP -- Target another creature, who replaces you as the carrier of the disease.

* *Purifying flame*.
_Touch_, _stretch_.
Target an unlit light source, such as a _candle_, an _oil lamp_, a _torch_, or a bonfire. It is instantly lit with a bright white flame. All creatures it illuminates are immune to poison and disease. If they are already _poisoned_, the poison isn't neutralized but its effect is suspended. If they are already _sick_, they aren't healed but they don't suffer negative effects if they fail a recovery roll.


* *Radiant honesty*.
_Touch_, _stretch_.
Target a creature of human intelligence. The target is unable to lie, but also exudes trustworthiness and automatically succeed at reasonable persuasion attempts.


* *Reanimate corpse*.
_Touch_, _stretch_.
Target the corpse of a medium-sized or smaller creature. It is raised as a _reanimated corpse_ under your control (see the Bestiary chapter for relevant stats and rules).

** 2 EP -- Increase the maximum size of the targeted corpse by one category.

* *Silence*.
_Touch_, _stretch_.
Target a zone. No sound can be produced or heard within it. Among other things, it isn't possible to invoke powers while inside the zone, but spells can still be cast from outside into it.


* *Star sign*.
_Sight_, _stretch_.
Target a celestial body (the Sun, the Moon, a planet, a star, etc.) at any range. You can subtly alter its appearance (make it slightly larger, smaller, brighter, darker, etc.). You can keep altering appearance as long as you concentrate, otherwise it remains as you left it until the spell is over. Characters with the _erudition_ skill can tell something is different, even if subtle.It is said that some wizards use this spell to encode messages in the stars.

** 2 EP -- You can alter target's appearance in a rather evident way, so that pretty much everyone can see the difference.

* *Summon demon*.
_Touch_, _stretch_.
Target a zone and invoke the true name of a _demon_. The veil between reality and the netherworld is torn, and the demon steps into this world. The demon isn't under the caster's control and behaves according to its own desires.

** 2 EP -- The demon must fulfil a demand when summoned, after which it's free. It can still refuse to obey, in which case it is paralysed as if bound by invisible chains. If that happens, you can attempt to bargain and strike some sort of compromise. Typically, demons will be more willing to grant better boons if summoned for longer.

* *Water breathing*.
_Touch_, _stretch_.
Target a creature. Gills and fins appear on the target's body, and their hands, feet, or paws become palmate. The target can breathe underwater and can swim as naturally as they can walk.


* *Wood shape*.
_Touch_, _stretch_.
Target a creature. The target turns into a tree. They are still able to perceive their surroundings.


