== Miscellanea

* *Animal skin* (4ʂ).
Skin of a small animal. Multiply cost by 4 and bulk by 2 for each size above small.

* *Cage* (16ʂ, bulk 2).
Can contain a small character.

* *Crutch* (4ʂ).
_Hobbled_ characters can use it to walk.

* *Divination tools* (16ʂ, bulk 2).
Include a crystal ball, tarot cards, divination bones, etc. Used in combination with the _divination_ skill.

* *Junk* (1ʂ).
Skull, bag of dirt or dung, dirty pillow, chalk...

* *Ladder* (4ʂ, bulk 4).
Climbing it is trivial.

* *Lockbox & key* (4ʂ).
Can contain a total bulk of 1.

* *Looking glass* (16ʂ).
See distant details.

* *Lucky charm* (16ʂ, bulk ½).
When you spend an omen, there is 1:4 chance it isn't actually spent. If combined with the _lucky_ skill, You have in total a 1:2 chance of not losing the omen.

* *Manacles & key* (4ʂ).
Used to bind someone's hands.

* *Mirror* (16ʂ).
A simple hand mirror.

* *Music instrument* (16ʂ).
Drums, fiddle, flute, lyre, lute, etc.

* *Perfume* (16ʂ, bulk ½).
_Consumable_.
An exquisite perfume.

* *Pipe & tobacco* (4ʂ, bulk ½).
_Consumable_.
Smoke it after failing a save in a situation requiring thinking to repeat the save once. Then pass a WIT save or become _addicted_ to it.

* *Prosthesis* (16ʂ).
Replaces a lost limb. Works as a _crutch_ if it replaces a lost leg.


* *Saddle* (16ʂ, bulk 2).
Required to ride a mount. Includes saddlebags.

* *Sealing wax* (4ʂ, bulk ½).
_Consumable_.
Used to seal letters in combination with a _signet ring_.

* *Signet ring* (16ʂ, bulk ½).
Proof of identity, used to stamp _sealing wax_.

* *Toolbox* (16ʂ, bulk 2).
Includes hammer, saws, nails, etc. Spend a watch and pass a WIT save to repair a damaged item, but on a fail it is destroyed. If the item has the _health_ property, repair or inflict 2 damage instead on a pass or fail.

* *Wooden pole* (4ʂ, bulk 2).
2 metre long.

