== Profane powers

* *Animal shape*
Target a _creature_, who turns into a medium-sized animal of your choice. You must carry the skin, feathers, scales, or shell of the chosen animal, which envelop and merge with the target during the transformation and returns to its previous state when the spell ends. The target keeps WIT and intelligence level, but can't speak. The spell doesn't influence the target's equipment, which simply falls to the ground.
* 2 EP -- Turn into a _small_ or _large_ animal. By applying this enhancement twice, you can turn into a _tiny_ or _massive_ animal.

* *Arcane lock*
Target an item which can be opened and closed, such as a door, a box, or a bottle. The target can only be opened by a trigger of your choice (a password, a gesture, contact with a specific item...).
* 1 EP -- The target emits a loud sound if someone attempts to open it without using the proper method.

* *Bewitch*
Target a creature. The target attitude towards you improves by a step: hostile to unfriendly, unfriendly to neutral, neutral to friendly, friendly to infatuated (see the Encounters chapter).
* 1 EP -- Improve the attitude by an additional step
* 1 EP -- Target another creature, who replaces you as the one towards whom attitude is improved.

* *Burning vengeance*
Target a creature with human intelligence. Name a person they know and remind how they have been wronged by them, no matter if by a small or a big matter. The target becomes obsessed with an irrational desire to take revenge by killing the named person, and they will fully devote themselves to this end.

* *Eldritch blast*
Target a character or an item. The target is hit by a force blast, which works as a melee attack, inflicting d10 damage (impaired against items). If you enhance the power to _sight_ range, it works as a ranged attack instead. All skills and rules concerning attacks apply, and the attack can be dodged or countered as usual. If you enhance the power to _connection_ range, the blast is conjured on top of the target and your skills don't apply any longer, but the target can still dodge.
* 1 EP -- The power inflicts fire, lightning, cold, or heat damage.

* *False death*
Target a _creature_. The target falls like a string-less puppet and appears dead, even upon close examination. However, they are still very much alive: they can perceive their surroundings and must breathe, eat, and drink to survive.

* *Fiery taste*
Target up to 4 _rations_ and/or _alcoholic drinks_. _Rations_ become extremely spicy: those who consume must pass a STR save or succumb to a terrible stomachache and be _incapacitated_ until the end of the stretch. _Alcoholic drinks_ become extremely potent: drinking one counts as drinking two. Characters with the _fire eating_ skill aren't affected.

* *Flawed resurrection*
Target the lifeless heart of a _creature_ who died no longer than a stretch ago. A new body forms around the heart and the target's spirit is called back to inhabit it, effectively resurrecting them. The regeneration process takes a day and the new body is different from the original both in appearance and capabilities. STR and AGI are equal to the average (8 for humans, what's indicated in their profile for other creatures) minus d3. WIT, skills, intelligence, and personality don't change. Once the resurrection is complete, the target immediately suffers 4 corruption.
* 2 EP -- Accelerate the regeneration process: from a day to a watch, then from a watch to a stretch.
* 2 EP -- Target a _creature_ who died longer than a stretch ago: from a stretch to a watch, from a watch to a day.

* *Gift of speech*
Target a creature with animal intelligence or human intelligence. The target gains the ability to speak your language.

* *Hold secret*
Target a _creature_ of _human intelligence_ and name a topic. The target is physically unable to talk about the topic, and if forced to, they will compulsively lie.

* *Illusion*
Target a small zone. You can create an illusion within its boundaries. The illusion can affect sight, hearing, and smell, but not touch. While you are within range, you can concentrate on the illusion to change it or animate it. While you aren't concentrating, the illusion remains frozen in the state you left it, and only disappears when the power ends.

* *Joyous appearance*
Target a _creature_. The target's appearance becomes perfect and free of any blemish. Signs of disease, affliction, old age, and mutation completely disappear. The appearance might in fact be too perfect, almost uncanny (the skin is too smooth, the cheeks are too rosy...). The change in appearance is real, not an illusion, but any underlying illness or problem isn't cured and still has effect.

* *Levitation*
Target a creature. The target temporarily gains the _landing flyer_ trait.
* 1 EP -- Improve flying by a category: _landing flyer_ to _swooping flyer_, _swooping flyer_ to _hovering flyer_.

* *Miasma of chaos*
Target a small zone. The area is filled with red mist flowing from the ground. Characters entering or starting their turn in the affected area suffer 1 corruption. The mist blocks visibility.
* 1 EP -- Double the amount of corruption.
* 1 EP -- The mist covers all zones within range 1 of the targeted one. Enhance again to double the range.

* *Occult consultation*
Target the corpse of a creature who has died no longer than a stretch ago and whose spirit is still lingering in the area. You may ask the spirit one question, but they aren't forced to answer truthfully, or at all. If you enhance the power range to _connection_, you may contact the spirit of a long dead person, but they can only answer by knocking on the door to the underworld: their answer can only be a number, yes, or no.

* *Plague vessel*
Target a _sick_ creature. You absorb the disease from the target, who is instantly healed. You carry the disease in your body without suffering its effect. You can attempt to discharge it by touching another creature before the power ends. The target can resist the infection with a STR save. If they resist, the disease stays in your body, and you can attempt to discharge it again later. If the power ends before you discharge the disease, you are infected by it yourself, without chance of a save.
* 1 EP -- Target another creature, who replaces you as the carrier of the disease.

* *Purifying flame*
Target an unlit light source, such as a _candle_, an _oil lamp_, a _torch_, or a bonfire. It is instantly lit with a bright white flame. All creatures illuminated by it are immune to poison and disease. If they are already poisoned, the poison isn't neutralized but its effect is suspended while under the light. If they are already _sick_, they aren't healed but don't suffer negative effects if they fail a recovery roll while under the light.

* *Radiant honesty*
Target a _creature_ of _human intelligence_. The target is unable to lie, but also exudes trustworthiness and reduces the difficulty of persuasion attempts.

* *Reanimate corpse*
Target the corpse of a medium-sized (or smaller) creature. It is raised as a _reanimated corpse_ under your control (see the Bestiary chapter for relevant stats and rules).
* 2 EP -- Increase the maximum size category of the targeted corpse by one step.

* *Silence*
Target a zone. No sound can be produced or heard within it. Among other things, it isn't possible to invoke powers while inside the zone, but spells can still be cast from outside into it.

* *Star sign*
Target a celestial body (the Sun, the Moon, a planet, a star...) at any range. You can subtly alter its appearance (make it slightly larger, smaller, brighter, darker...). You can keep altering appearance as long as you concentrate, otherwise it remains as you left it until the spell is over. Characters with the _erudition_ skill can tell something is different, even if subtle. It is said that some wizards use this spell to encode messages in the stars.
* 2 EP -- You can alter target's appearance in a rather evident way, so that pretty much everyone can see the difference and not just erudite characters.

* *Summon demon*
Target a zone and invoke the true name of a _demon_. The veil between reality and chaos is torn and the demon steps into this world. The demon isn't under the caster's control and behaves according to its own desire.
* 2 EP -- The demon must fulfil a demand when summoned, after which it's free. It can still refuse to obey, in which case it is paralysed as if bound by invisible chains. You can attempt to bargain and change the request.

* *Water breathing*
Target a creature. Gills and fins appear on the target's body and their hands, feet, or paws become palmate. The target can breathe underwater and can swim at full speed.

* *Wood shape*
Target a _creature_. The target turns into a tree. They are still able to perceive their surroundings.

