== Academic gear

* *Scroll* (1ʂ, bulk ½).
The price is for a blank scroll.


* *Book* (16ʂ).
The price is for a blank book. Written books can cost 64ʂ or even more.


* *Power scroll* (64ʂ, bulk ½).
A scroll recording a sacred or profane power. The knowledge of how to write them has been lost.


* *Grimoire* (16ʂ).
Can hold up to 4 _power scrolls_, removing the need to swamp them out to invoke their power.


* *Quill & ink* (4ʂ, bulk ½).
Used to write on scrolls and books.


* *Sacred relic* (1024ʂ).
The remains of a dead saint. Priests holding it can re-roll the d12 when checking if invoking a sacred power is successful.


* *Vim* (64ʂ, bulk ½).
_Consumable_.
Pure, concentrated magical essence. Sorcerers can consume it to invoke a profane power without spending mana _or_ with an additional EP. Bringing more than 2 doses of vim within the same zone can cause them to explode: the chance is x-in-8, where x is the number of doses. If the explode, everyone in the zone suffers corruption equal to the amount of doses. If they didn't explode, re-roll at the start of the next stretch.


