== Skill list

* *Acrobatics*.
Proficient at balancing and leaping. Your attacks aren't impaired while balancing and leaping. You can perform a number of acrobatic performance acts, such as trampoline, trapeze, aerial silk...


* *Acting*.
Proficient at acting, storytelling, and disguising yourself. You can convincingly fake emotions, disguise your voice, imitate accents, and change your mannerism. This ability might provide you a proficiency advantage in situation where you can take advantage of it.


* *Alchemy*.
You are literate. You can speak Classic. You can craft alchemical substances, such as _acid vials_, _alchemist's fire_, _flash powder_, and _smoke bombs_, in a suitably equipped workshop. Knowledgeable about alchemical concepts, basic reactions, raw materials...


* *Ambidextrous*.
You can use both hands equally well. Damage is not impaired when you attack with a weapon in your non-dominant hand. You can attack the same target with two weapons at once, rolling damage for both but only considering the higher roll.


* *Animal handling*.
Proficient at taming, training, befriending, and in general interacting with animals. Knowledgeable about animal care: feeding, grooming, training, taming, understanding needs...


* *Bargain*.
If you have this skill, you purchase items at half price unless the seller also has this skill. You are able to accurately estimate the value of most items by taking a look at them.


* *Battle frenzy*.
You can become _frenzied_ by spending a round inciting yourself into a frothing rage, or immediately when you suffer damage. The condition lasts until all enemies have been defeated or you spend a round trying to calm yourself and pass a WIT save. While _frenzied_, you recover 1 health for each enemy you kill.


* *Blather*.
Proficient at distracting and taunting. You are able to speak endless strings of nonsense, leaving people dumbfounded. If you spend a stretch chatting with someone, you understand what might make them angry.


* *Bravery*.
You are immune to fear and treat terror as fear.


* *Brawling*.
Your unarmed attacks are not impaired and inflict d6 damage. You have an innate armour value of 1 against unarmed attacks, however you lose this advantage if you wear armour.


* *Burglary*.
Proficient at picking and forcing locks. You can react to all traps you trigger, even if you weren't aware of them.


* *Bushcraft*.
Proficient at finding drinking water and shelter in the wilderness. You can efficiently lead the way through the wilderness, ignoring the movement penalty when travelling without following a path if you pass a WIT save. If you have _navigation tools_ as well, you pass automatically. When you forage, you roll twice on the foraging table and apply both results. Knowledgeable about orientation in the wilderness, common plants, and survival.


* *Charm*.
Proficient at befriending and persuading. If you spend a stretch chatting with someone, you understand what it might take to befriend or persuade them, if they are bribable, and so on.


* *Cleave*.
When you inflict critical damage or kill a target with a melee attack, you can immediately attack another target with the same weapon. You can do this at most once per turn.


* *Climb*.
Proficient at climbing. > Your attacks aren't impaired while climbing. > You reduce falling distances by 2 metres to determine how much damage you suffer.


* *Contortionist*.
Your joints are extremely flexible and you can bend your body in absurd shapes. You can squeeze through small openings and easily escape bonds.


* *Craft medicine*.
You can craft medicinal substances, such as _antidotes_, _cure-alls_, _healing draughts_, _medicine boxes_, and all kinds of drugs, using _apothecary tools_. Knowledgeable about medicinal ingredients, herbalism...


* *Craft poison*.
You can craft all kinds of poisons using _apothecary tools_. Knowledgeable about different types of poisons, their effect, how to neutralise them...


* *Crafting*.
You can craft a number of different non-consumable items equal to half your WIT, and you are proficient at repairing them. You don't have to choose immediately what you can craft: as long as you still have free '`slots`', you can decide on the moment. Keep track of what items you can craft. Knowledgeable about smithing, carpentry, tannery, and other forms of crafting.


* *Dark vision*.
You can see better than most under dim lighting, and you are used to rely on senses other than sight (hearing, smell, touch). This is no supernatural power: you still can't see anything in total darkness! You can see one zone further in areas illuminated by a light source such as a candle or a torch. Your melee attacks always hit even if you can't see the target, as long as you can hear them or detect them otherwise. In general, the GM might let you ignore penalties related to darkness or dim lighting when deemed appropriate.


* *Disarm*.
Targets of your disarm attacks can't resist with a STR save unless they also have this skill. You can only be disarmed by characters with this skill.


* *Disease resistance*.
After encountering a new disease, you develop an immunity to it. The first time you must still make a STR save to check if you get sick, and if you do you follow the normal rules, but afterwards you are completely immune. Keep track of the diseases you are immune to.


* *Divination*.
If you have _divination tools_, you can spend an omen and a stretch of time to ask a question pertaining your current situation. The GM describes a vision giving you a cryptic answer. There is a 1:4 chance that the vision is wrong or misleading, rolled secretly by the GM. Knowledgeable about astrology and fortune telling.


* *Dodge blows*.
You can dodge without spending your turn once per round.


* *Drive carts*.
Proficient at driving carts, coaches, chariots, sledges, and other land vehicles. Your attacks aren't impaired when on such a vehicle. You can attack after your vehicle makes a full movement. Knowledgeable about road travel.


* *Erudition*.
You are literate. You can speak Classic. Knowledgeable in all fields of academic lore: history, geography, beasts, plants, philosophy, mathematics, astronomy...


* *Faith*.
You are literate. You can speak Classic. You can invoke sacred powers. Knowledgeable about religion, theology, sacred texts...


* *Fast strike*.
When you counter an attack or your attack is countered, you always hit first unless your opponent also has this skill.


* *Fire eating*.
You can consume an _alcoholic drink_ and spit it through an open flame, such as a lit _torch_, to make a melee blast attack inflicting d4 fire damage. The normal effects of the _alcoholic drink_ of course don't apply in this case. You reduce incoming fire damage by 1.


* *Fleet footed*.
Proficient at sprinting. You can renounce your proficiency advantage to sprint by an additional zone. You can freely dodge attacks of opportunity without needing to spend your turn.


* *Frugal*.
You can get by with very little. On a day rest, you recover health and mana even if you don't satisfy all daily needs. You pay half for lodging.


* *Gossip*.
Proficient at gathering information and finding contacts in settlements, for example for trading specific goods. Whenever you take a day rest or full rest in a settlement, you hear interesting rumours. The GM decides what you hear, and it isn't necessarily true.


* *Heal*.
Proficient at performing surgeries. Knowledgeable about all kinds of wounds and injuries and ways to treat them. When you use a _medicine box_: heal half STR in a stretch, or d8 damage (up to half STR) in a round.


* *Hunt*.
Proficient at following trails. Knowledgeable about local fauna, how to hunt them... When you forage, on a _small game_ result you gain an additional _ration_, even if you don't have _trapping tools_.


* *Incorruptible*.
You suffer half the normal amount of corruption. However, you can't voluntarily suffer corruption, for example to invoke profane powers.


* *Intimidate*.
Proficient at intimidating and torturing. If you spend a stretch talking with or observing someone, you understand what might frighten them.


* *Languages*.
You are literate. You can speak a number of additional languages equal to half your WIT. You don't have to choose immediately what language you can speak: when you encounter a new one in your adventures, you can choose if you can speak it. Keep track of what languages you can speak.


* *Leadership*.
Proficient at inspiring and keeping the loyalty of followers. Once per stretch, you can spend a round to rally all _frightened_ and _terrified_ allies within range 2. They make a group WIT save and those who succeed recover immediately


* *Lucky*.
Your maximum omens are increased by 1. When you use an omen, there is a 1:4 chance it isn't actually spent. When choosing the target of an indiscriminate effect, such as a trap or a monster ambush, the GM might prioritise other characters over you.


* *Magic sense*.
You can spend a stretch in meditation to sense the presence of magic phenomena (ongoing powers, demons, magical creatures...) in your zone or in your sector (your choice). You can only detect if any magic phenomena is present in the area, but can't count them, locate them, or determine their nature.


* *Magic shield*.
You can use an ancient esoteric technique to erect a magic shield around you. Activating or deactivating it takes a stretch spent in meditation, and it deactivates automatically if you are _incapacitated_ or fall asleep. Profane powers have a 1:2 chance of not working on you, no matter if harmful or beneficial. Sorcerers can spend 1 enhancement point to ignore the shield.


* *Medicine*.
You are literate. You can speak Classic. Knowledgeable about human anatomy and physiology, illnesses, and ailments. You can diagnose poison and disease by spending a round examining a patient. After diagnosing, you can instruct someone with the _apothecary_ skill to create a bespoke _antidote_ or _cure-all_ which is guaranteed to work.


* *Meditation*.
You heal 1 corruption on a day rest, and all corruption on a full rest.


* *Monster slaying*.
You inflict double damage against targets of larger size category.


* *Music*.
Proficient at singing and playing music. Knowledgeable about music theory, instruments, famous musicians... During a day rest you can play an inspiring song for the company: all companions have a 1:4 chance of recovering a spent omen.


* *Pack rat*.
Your carry limit is increased by 2 (you can carry up to 10 bulk unencumbered, and up to 20 bulk encumbered). Your own bulk doesn't change.


* *Piercing strike*.
If you roll damage higher than your target's armour value, you completely ignore armour and inflict the full amount of damage. This skill doesn't work in situations where you are required to pass a WIT save to hit, as it requires full precision.


* *Play games*.
Proficient at playing games. Your cheating attempts are always successful unless your opponents are paying close attention to you. People might still get suspicious if you win too much.


* *Poison resistance*.
You are resistant to alcohol, poisons, and drugs. You may ignore the first dose taken within a stretch. You can resist a second dose with a STR save, and a third dose works automatically.


* *Political lore*.
You are literate. You can speak Classic. Knowledgeable in laws, politics, structures of power...


* *Protect*.
You can guard without spending your turn any number of times.


* *Quick draw*.
You can equip and unequip any number of items held in hand as a single bonus action.


* *Ride*.
Proficient at riding animals. Your attacks aren't impaired while riding. You can attack after your mount makes a full movement. Knowledgeable about taking care of mounts, controlling them...


* *River lore*.
Proficient at driving boats, rafts, and other waterborne vehicles. You count as two people when rowing a boat and you can handle a sailing boat. Your attacks aren't impaired when on such a vehicle. When you forage, on a _fish_ result you gain an additional _ration_, even if you don't have _fishing tools_. Knowledgeable about river travel.


* *Shield mastery*.
When you hold a shield, your armour value is increased by 1 against all attacks, not just if you react or are countered.


* *Skilled blow*.
You improve the damage die of melee attacks (excluding unarmed attacks): d4 to d6, d6 to d8, d8 to d10, d10 to d12. You can't improve a d12. In case of blast attacks, only one target takes increased damage.


* *Skilled shot*.
You improve the damage die of ranged attacks: d4 to d6, d6 to d8, d8 to d10, d10 to d12. You can't improve a d12. In case of blast attacks, only one target takes increased damage.


* *Sneak attack*.
You always inflict d12 damage when you attack unaware targets. Unarmed attacks are still impaired.


* *Sorcery*.
You are literate. You can speak Magick. You can invoke profane powers. When you advance, you can increase your maximum mana by 1 instead of learning a new skill or improving your abilities, up to 6 at most. Knowledgeable about magic, demonology, esoteric lore...


* *Steady aim*.
You double the range of ranged attacks.


* *Steal*.
Proficient at stealing items. You can quickly pocket small items (bulk of ½), making them almost instantly disappear in your clothes. They are almost impossible to find with a normal body search.


* *Stealth*.
Proficient at sneaking. When your group is detected by other characters, make an AGI save. If you pass, you manage to stay hidden even though your companions are detected.


* *Strike to injure*.
When you inflict critical damage, you may choose to injure or kill the target. You choose what injury to apply instead of rolling on the table (it must still make somewhat sense), and you may choose that it is permanent rather than temporary.


* *Strike to stun*.
When you attack with a blunt weapon (a cudgel, the pommel of a sword, a rock...) you may choose to inflict no lethal damage. You still roll the damage die and compare the result with the target's current health. If damage matches or exceeds half the target's remaining health, they are _incapacitated_ until the end of the stretch. If damage matches or exceeds the target's remaining health, they are _incapacitated_ until the end of the watch.


* *Swim*.
Proficient at swimming. Your attacks aren't impaired while swimming. You can hold your breath for twice as long (normally 8 rounds instead of 4).


* *Tough*.
Your maximum health, as well as the threshold for instant death, are increased by 2 (they equal your STR plus 2).


* *Wrestling*.
Targets of your grapple attacks can't resist with a STR save unless they also have this skill. You can only be grappled by characters with this skill.


