== Survival gear

* *Ration* (4ʂ, bulk ½)
_Consumable_.
Enough food for a daily rest.


* *Water* (1ʂ, bulk ½)
_Consumable_.
Enough to drink for a daily rest.


* *Alcoholic drink* (4ʂ, bulk ½)
_Consumable_.
Recover 1 health unless you are _dying_. Pass a STR save or become _groggy_ until the end of the stretch.


* *Camping kit* (16ʂ, bulk 2)
Includes a bedroll, blankets, and tent space for one person. Necessary to sleep in the wilderness.


* *Field kitchen* (16ʂ, bulk 2)
Includes pots, pans, kitchen utensils, etc. Food you gather by foraging is doubled and doesn't go bad.


* *Fishing tools* (16ʂ, bulk 2)
Obtain a _ration_ on a _fish_ result while foraging.


* *Trapping tools* (26ʂ, bulk 2)
Obtain a _ration_ on a _small game_ result while foraging.


* *Navigation tools* (16ʂ, bulk 2)
Include maps, compass, etc. You can efficiently navigate the wilderness: you only halve your movement speed instead of reducing it to ¼.


* *Warm clothes* (16ʂ, bulk 2)
Work like _clothes_, however cold damage is impaired and heat damage is enhanced.


